// R-F3332 — an ISSUED temporary password must be rotated before the account works.
//
// R-F3328 made design-partner approval mint a one-time password. That credential
// is generated by us, displayed on an admin's screen and emailed in clear, so it
// is known to at least one other party by construction — unlike a password the
// user chose at signup. The email and the admin panel both INSTRUCT the partner
// to change it, and instruction is not enforcement: nothing stopped it living
// for the life of a full-platform proIntel account.
//
// The gate is a pure function (lib/auth/passwordRotation.mjs) that requireAuth
// calls, rather than a condition buried in middleware, so these tests drive THE
// REAL DECISION rather than a copy of it. The source lock below asserts
// requireAuth actually calls it — a perfect decision function nothing invokes is
// the "producer with no carrier" defect, and it would pass every test here.
//
// Run: node --test test/issued-credential-must-rotate-rf3332.test.mjs
import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, readFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const REPO = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');

// Module-scope awaits BEFORE the first test() — R-F3331: a test registered after
// one of these is silently cancelled by --test-force-exit.
const STORE = path.join(mkdtempSync(path.join(tmpdir(), 'users-rf3332-')), 'users.json');
process.env.USERS_FILE_OVERRIDE = STORE;
process.env.JWT_SECRET = process.env.JWT_SECRET || 'test-secret-rf3332-at-least-32-characters-long';

const { findUserByEmail, verifyPassword, updateUser, hashPassword } =
  await import('../lib/auth/users.mjs');
const { provisionDesignPartnerAccess } = await import('../lib/auth/designPartnerAccess.mjs');
const { rotationBlocked, rotationClearedFields, ROTATION_ALLOWED, ROTATION_REQUIRED_CODE } =
  await import('../lib/auth/passwordRotation.mjs');

const noopMailer = async () => ({ sent: false, reason: 'test' });

// ── The property, on the real decision ───────────────────────────────────────

test('R-F3332: a provisioned partner is refused on an ordinary API call', async () => {
  const r = await provisionDesignPartnerAccess(
    { name: 'Locked Partner', contact: 'locked@rf3332.test' }, { sendEmail: noopMailer });
  assert.equal(r.provisioned, true, r.reason);

  const user = findUserByEmail('locked@rf3332.test');
  assert.equal(user.mustChangePassword, true, 'provisioning must flag the issued credential');
  assert.equal(rotationBlocked(user, 'GET', '/api/dd/reports'), true);
  assert.equal(rotationBlocked(user, 'POST', '/api/aria/chat'), true);
});

test('R-F3332: the locked account can still do the three things that unlock it', () => {
  const user = findUserByEmail('locked@rf3332.test');
  for (const { method, path: p } of ROTATION_ALLOWED) {
    assert.equal(rotationBlocked(user, method, p), false, `${method} ${p} must stay reachable`);
  }
});

test('R-F3332: the allowlist is method-specific, not path-specific', () => {
  const user = findUserByEmail('locked@rf3332.test');
  // /api/auth/me is readable; that must not hand over every verb on the path.
  assert.equal(rotationBlocked(user, 'GET', '/api/auth/me'), false);
  assert.equal(rotationBlocked(user, 'DELETE', '/api/auth/me'), true);
  assert.equal(rotationBlocked(user, 'POST', '/api/auth/password'), true);
});

test('R-F3332: a query string cannot change the decision', () => {
  const user = findUserByEmail('locked@rf3332.test');
  assert.equal(rotationBlocked(user, 'GET', '/api/auth/me?x=1'), false,
    'an allowed path stays allowed with a query string');
  assert.equal(rotationBlocked(user, 'GET', '/api/dd/reports?/api/auth/me'), true,
    'a blocked path cannot be smuggled past by putting an allowed one in the query');
});

test('R-F3332: rotating the password unlocks the account', () => {
  const before = findUserByEmail('locked@rf3332.test');
  // Exactly what PUT /api/auth/password writes.
  updateUser(before.id, { passwordHash: hashPassword('a-real-password'), ...rotationClearedFields() });

  const after = findUserByEmail('locked@rf3332.test');
  assert.equal(after.mustChangePassword, false);
  assert.ok(after.credentialRotatedAt, 'the rotation must be stamped');
  assert.equal(rotationBlocked(after, 'GET', '/api/dd/reports'), false, 'the account is usable again');
  assert.equal(verifyPassword('a-real-password', after.passwordHash), true);
});

test('R-F3332: an ordinary user is untouched by the gate', () => {
  // Everyone who chose their own password at signup has no flag, and a rule
  // this blunt must not reach them.
  assert.equal(rotationBlocked({ id: 'x', status: 'active' }, 'GET', '/api/dd/reports'), false);
  assert.equal(rotationBlocked(null, 'GET', '/api/dd/reports'), false,
    'no live user record (service caller) must not be blocked');
});

// ── The carrier: the gate is actually wired ──────────────────────────────────

test('R-F3332: requireAuth enforces the gate, on the LIVE record not the JWT', () => {
  const src = readFileSync(path.join(REPO, 'server.mjs'), 'utf-8');
  const fn = src.slice(src.indexOf('function requireAuth(req, res, next)'));
  const body = fn.slice(0, fn.indexOf('\nfunction '));

  assert.ok(/rotationBlocked\(liveUser,\s*req\.method,\s*req\.path\)/.test(body),
    'requireAuth must call rotationBlocked with the live user record — the JWT is a '
    + 'login-time snapshot and cannot know about a flag set after it was minted');
  assert.ok(body.includes('ROTATION_REQUIRED_CODE'),
    'the refusal must carry the machine-readable code the client redirects on');
  assert.ok(/return res\.status\(403\)/.test(body), 'the refusal must be a 403');
});

test('R-F3332: the password-change route clears the flag', () => {
  const src = readFileSync(path.join(REPO, 'server.mjs'), 'utf-8');
  const route = src.slice(src.indexOf("app.put('/api/auth/password'"));
  const body = route.slice(0, route.indexOf('\napp.'));
  assert.ok(/rotationClearedFields\(\)/.test(body),
    'the only route that can satisfy the gate must also clear it, or a rotated '
    + 'account stays locked out for ever');
});

test('R-F3332: the client redirect target is self-contained', () => {
  // R-F3311's lesson: sending a locked user to a page whose shared shell calls a
  // blocked endpoint produces a bounce loop, not a fix.
  const page = readFileSync(path.join(REPO, 'public', 'set-password.html'), 'utf-8');
  assert.ok(!/sidebar\.js/.test(page), 'must not load the shared shell');
  assert.ok(!/Sidebar\.init/.test(page), 'must not call Sidebar.init (it fetches /api/auth/me + more)');

  const calls = [...page.matchAll(/API\.(get|post|put|del|probe)\('([^']+)'/g)].map((m) => m[2]);
  const allowed = new Set(ROTATION_ALLOWED.map((a) => a.path));
  for (const c of calls) {
    assert.ok(allowed.has(c), `set-password.html calls ${c}, which the gate blocks`);
  }

  const app = readFileSync(path.join(REPO, 'public', 'js', 'app.js'), 'utf-8');
  assert.ok(app.includes(`data.code !== '${ROTATION_REQUIRED_CODE}'`)
         || app.includes(`data.code === '${ROTATION_REQUIRED_CODE}'`),
    'app.js must react to the server code, not to a bare 403');
  assert.ok(/set-password\\.html\$\/\.test\(window\.location\.pathname\)/.test(app),
    'the redirect must refuse to target the page it is already on (loop guard)');
});

test('R-F3332: signin sends a flagged user to set a password, on BOTH login paths', () => {
  // The 2FA branch is a second, separate redirect — a gate wired into only the
  // password path would be silently bypassed by any user with 2FA enabled.
  const page = readFileSync(path.join(REPO, 'public', 'signin.html'), 'utf-8');
  const hits = page.match(/mustChangePassword\)\s*\r?\n?\s*\?\s*'\/set-password\.html'/g) || [];
  assert.equal(hits.length, 2,
    `both doLogin and do2FA must route a flagged user to set-password.html; found ${hits.length}`);
});
