# fly.toml app configuration file generated for aria-intel on 2026-05-31T23:22:36Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'aria-intel'
primary_region = 'lhr'

[build]
  dockerfile = 'aria_service/Dockerfile'

[env]
  HF_HUB_DISABLE_TELEMETRY = '1'
  HF_HUB_OFFLINE = '1'
  TRANSFORMERS_OFFLINE = '1'

[[mounts]]
  source = 'aria_rag'
  destination = '/data'
  initial_size = '5gb'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

  [[http_service.checks]]
    interval = '1m0s'
    timeout = '1m0s'
    grace_period = '1m30s'
    method = 'GET'
    path = '/api/aria/health/live'

[[vm]]
  size = 'shared-cpu-4x'
  memory = '8192mb'
