#!/usr/bin/env python
"""self_critique_sample — DeepSeek fact-check sweep over the distillation corpus.

R-F1470 / §24 dataset-quality gate. Implements ARIA's R-F1468 #1b self-critique
plan: a SEPARATE DeepSeek call per sampled pair asks "is this answer fabricated /
wrong / vague?" and aggregates a fabrication rate. This is NOT self-grading
(generator==judge rubber-stamp) — it is a distinct fact-check pass that catches
the egregious fabrications DeepSeek demonstrably makes (Saudi-source fabrication,
Mozambique/Wassenaar error seen in the judge eval).

Sampling: stratified, N per topic (default 3). Decision framework (ARIA):
  fabrication_rate <5%  -> accept as-is
  5-15%                 -> accept with eyes open (note rate in the runbook)
  >15%                  -> filter the corpus before training

Env: DEEPSEEK_API_KEY (loaded from .env if not already set).

Usage:
    python scripts/train/self_critique_sample.py \
        --corpus data/training/aria_sft_distill_500.jsonl --per-topic 3
"""
from __future__ import annotations

import argparse
import asyncio
import json
import os
import random
import sys
from collections import Counter, defaultdict
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parents[2]

_SYSTEM = (
    "You are a strict fact-checker. The following is a question and an answer "
    "generated by an AI. Your job is to identify any fabricated specifics, "
    "factual errors, or ungrounded claims in the answer. Be specific — cite the "
    "exact claim and explain why it's wrong or unverifiable.\n\n"
    "Rules:\n"
    "- \"CLEAN\" = all claims in the answer are factually correct and grounded in public knowledge\n"
    "- \"FABRICATION\" = the answer contains specific numbers, dates, names, or events that are invented or cannot be verified\n"
    "- \"ERROR\" = the answer makes a factual mistake (wrong jurisdiction, wrong regulation, wrong threshold, etc.)\n"
    "- \"VAGUE\" = the answer is technically correct but so generic/evasive it provides no useful information\n"
    "- If the answer refuses to answer (ground-or-abstain), mark it CLEAN — that's correct behaviour\n\n"
    "Return ONLY one JSON object:\n"
    '{"verdict": "CLEAN|FABRICATION|ERROR|VAGUE", "reason": "<one sentence explaining the issue>", '
    '"flagged_claims": ["<specific claim 1>", "<specific claim 2>"]}'
)


def _load_dotenv() -> None:
    env_path = _REPO_ROOT / ".env"
    if not env_path.exists():
        return
    for line in env_path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, _, v = line.partition("=")
        k, v = k.strip(), v.strip().strip('"').strip("'")
        if k and k not in os.environ:
            os.environ[k] = v


async def _critique(client, url, model, key, question: str, answer: str) -> dict:
    import httpx
    body = {
        "model": model,
        "messages": [
            {"role": "system", "content": _SYSTEM},
            {"role": "user", "content": f"QUESTION:\n{question}\n\nANSWER:\n{answer}"},
        ],
        "max_tokens": 400,
        "temperature": 0.0,
    }
    headers = {"Content-Type": "application/json", "Authorization": f"Bearer {key}"}
    try:
        resp = await asyncio.wait_for(
            client.post(f"{url}/chat/completions", headers=headers, json=body), timeout=100.0
        )
        if resp.status_code != 200:
            return {"verdict": "UNSCORED", "reason": f"http_{resp.status_code}"}
        raw = resp.json()["choices"][0]["message"]["content"].strip()
        import re
        raw = re.sub(r"^```(?:json)?\s*|\s*```$", "", raw, flags=re.IGNORECASE).strip()
        obj = json.loads(raw)
        v = str(obj.get("verdict", "UNSCORED")).upper()
        if v not in ("CLEAN", "FABRICATION", "ERROR", "VAGUE"):
            v = "UNSCORED"
        return {"verdict": v, "reason": obj.get("reason", ""), "flagged_claims": obj.get("flagged_claims", [])}
    except Exception as e:
        return {"verdict": "UNSCORED", "reason": f"exc: {e}"}


async def _run(args) -> int:
    _load_dotenv()
    key = (os.environ.get("DEEPSEEK_API_KEY") or os.environ.get("ARIA_DEEPSEEK_API_KEY") or "").strip()
    if not key:
        print("FATAL: DEEPSEEK_API_KEY not set (checked env + .env)")
        return 2
    url = os.environ.get("ARIA_DEEPSEEK_URL", "https://api.deepseek.com/v1")
    model = os.environ.get("ARIA_DEEPSEEK_MODEL", "deepseek-chat")

    corpus = Path(args.corpus)
    records = [json.loads(l) for l in corpus.read_text(encoding="utf-8").splitlines() if l.strip()]
    by_topic: dict[str, list] = defaultdict(list)
    for r in records:
        by_topic[r.get("topic", "unknown")].append(r)

    if args.all:
        sample = list(records)
        print(f"[self_critique] {len(records)} records -> scoring ALL (filter mode)")
    else:
        rng = random.Random(42)  # nosec B311
        sample = []
        for t in sorted(by_topic):
            recs = by_topic[t]
            n = min(args.per_topic, len(recs))
            sample.extend(rng.sample(recs, n))  # nosec B311
        print(f"[self_critique] {len(records)} records, {len(by_topic)} topics -> sampling {len(sample)}")

    import httpx
    sem = asyncio.Semaphore(args.concurrency)
    done = {"n": 0}

    async def one(rec):
        async with sem:
            q = rec["messages"][0]["content"]
            a = rec["messages"][1]["content"]
            async with httpx.AsyncClient(timeout=90.0) as client:
                v = await _critique(client, url, model, key, q, a)
            v["topic"] = rec.get("topic")
            v["question"] = q[:90]
            v["_rec"] = rec  # keep the original for filtering
            done["n"] += 1
            if done["n"] % 50 == 0:
                print(f"[self_critique] scored {done['n']}/{len(sample)}")
            return v

    results = await asyncio.gather(*[one(r) for r in sample])

    # Filtered corpus: drop FABRICATION + ERROR; keep CLEAN/VAGUE/UNSCORED.
    if args.filter_out:
        kept = [r["_rec"] for r in results if r["verdict"] not in ("FABRICATION", "ERROR")]
        with open(args.filter_out, "w", encoding="utf-8") as f:
            for rec in kept:
                f.write(json.dumps(rec, ensure_ascii=False) + "\n")
        print(f"[self_critique] FILTERED corpus: kept {len(kept)}/{len(results)} -> {args.filter_out} "
              f"(dropped {len(results)-len(kept)} FABRICATION/ERROR)")

    for r in results:  # drop the bulky record before stats/serialisation
        r.pop("_rec", None)

    verdicts = Counter(r["verdict"] for r in results)
    total = len(results)
    scored = total - verdicts.get("UNSCORED", 0)
    denom = scored or 1
    fab = verdicts.get("FABRICATION", 0)
    err = verdicts.get("ERROR", 0)
    clean = verdicts.get("CLEAN", 0)
    vague = verdicts.get("VAGUE", 0)
    fab_rate = fab / denom
    err_rate = err / denom

    print("\n=== SELF-CRITIQUE RESULTS (DeepSeek fact-check) ===")
    print(f"sampled={total} scored={scored} unscored={verdicts.get('UNSCORED',0)}")
    print(f"CLEAN={clean} ({clean/denom:.1%}) | FABRICATION={fab} ({fab_rate:.1%}) | "
          f"ERROR={err} ({err_rate:.1%}) | VAGUE={vague} ({vague/denom:.1%})")
    print("\n-- flagged (FABRICATION/ERROR) --")
    for r in results:
        if r["verdict"] in ("FABRICATION", "ERROR"):
            print(f"  [{r['verdict']}] ({r['topic']}) {r['question']}... -> {r['reason'][:120]}")

    # Decision framework (ARIA) — keyed on fabrication rate
    print("\n=== VERDICT (§24 dataset-quality gate) ===")
    if fab_rate < 0.05:
        print(f"ACCEPT AS-IS — fabrication {fab_rate:.1%} < 5%. Corpus is good enough for the bootstrap cycle.")
    elif fab_rate <= 0.15:
        print(f"ACCEPT WITH EYES OPEN — fabrication {fab_rate:.1%} (5-15%). Note the rate in the runbook; "
              f"add the self-critique filter before scaling.")
    else:
        print(f"FILTER FIRST — fabrication {fab_rate:.1%} > 15%. Run self-critique on all {len(records)} "
              f"and exclude FABRICATION/ERROR before training.")

    if args.out:
        Path(args.out).write_text(json.dumps({
            "sampled": total, "scored": scored,
            "clean": clean, "fabrication": fab, "error": err, "vague": vague,
            "fabrication_rate": round(fab_rate, 4), "error_rate": round(err_rate, 4),
            "results": results,
        }, indent=2), encoding="utf-8", newline="\n")
        print(f"\n[self_critique] detail written to {args.out}")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--corpus", default="data/training/aria_sft_distill_500.jsonl")
    ap.add_argument("--per-topic", type=int, default=3)
    ap.add_argument("--all", action="store_true", help="score EVERY record (not a sample)")
    ap.add_argument("--filter-out", default="", help="write the filtered corpus (drop FABRICATION/ERROR) here")
    ap.add_argument("--concurrency", type=int, default=6)
    ap.add_argument("--out", default="data/eval_reports/self_critique_500.json")
    return asyncio.run(_run(ap.parse_args()))


if __name__ == "__main__":
    raise SystemExit(main())
