"""Render docs/cure/*.md from census.json. Read-only w.r.t. production code."""

import json
import re
import subprocess
import sys
from collections import Counter, defaultdict
from pathlib import Path

# CLAUDE.md §16: no hardcoded checkout path — derive from this file's location.
REPO = Path(sys.argv[1]).resolve() if len(sys.argv) > 1 else Path(__file__).resolve().parents[2]
OUT = REPO / "docs" / "cure"
OUT.mkdir(parents=True, exist_ok=True)
CENSUS = OUT / "census.json"

C = json.loads(CENSUS.read_text(encoding="utf-8"))
M = C["modules"]
PYM = {f: m for f, m in M.items() if m["lang"] == "python"}
NODEM = {f: m for f, m in M.items() if m["lang"] == "node"}

HEAD = (
    "<!-- GENERATED by the Cure Protocol Phase 0.2 census engine. Do not hand-edit;\n"
    "     re-run the census instead. Runtime proofs are absent until Phase 0.3. -->\n"
)
STAMP = subprocess.run(
    ["git", "rev-parse", "--short", "HEAD"], cwd=REPO, capture_output=True, text=True
).stdout.strip()


def banner(title: str, purpose: str) -> str:
    return (
        f"{HEAD}# {title}\n\n"
        f"**Crucix Cure Protocol — Phase 0.2 static census** · commit `{STAMP}` · "
        f"{C['counts']['tracked_files']} tracked files\n\n"
        f"{purpose}\n\n"
        "> **Proof status.** Every classification below carries a *static* proof and a\n"
        "> *test* proof. The **runtime proof is UNKNOWN** — Phase 0.3 (14-day production\n"
        "> overlay) has not been run. Per the three-proof rule (Phase 4.1), **nothing here\n"
        "> is deletable yet**: one proof missing means it stays DORMANT.\n\n"
    )


LEGEND = """## Classification legend

| Class | Meaning | Deletable? |
|---|---|---|
| `DEPLOY-ENTRYPOINT` | A Dockerfile `CMD`, `package.json` script, or CI step invokes it | No |
| `ACTIVE-STATIC` | Imported by non-test code (runtime use unconfirmed) | No |
| `DEPLOYED-DEP` | `COPY`d into an image, no importer found | No |
| `SERVED-ASSET` | Loaded by an HTML `<script src>` / `<link href>` | No |
| `SCRIPT-REFERENCED` | Only a dev `.sh`/`.ps1`/`Makefile` names it | No |
| `DORMANT` | Only tests reach it | No — needs runtime proof |
| `DEAD-CANDIDATE` | No importer, no entrypoint, no asset ref, no test | **Not yet** — needs Phase 0.3 + quarantine ladder |
| `TEST` | Test file | n/a |

"""


def table(rows, headers):
    out = ["| " + " | ".join(headers) + " |",
           "|" + "|".join("---" for _ in headers) + "|"]
    for r in rows:
        out.append("| " + " | ".join(str(x) for x in r) + " |")
    return "\n".join(out) + "\n"


# ------------------------------------------------------------------ modules.md
counts = Counter(m["classification"] for m in M.values())
pkg = defaultdict(Counter)
for f, m in M.items():
    top = "/".join(f.split("/")[:2]) if "/" in f else "(root)"
    pkg[top][m["classification"]] += 1

lines = [banner("modules.md — module census",
                "Every tracked Python and Node module, its importers, its entrypoints, "
                "and whether anything reaches it at all."), LEGEND]

lines.append("## Totals\n")
lines.append(table([[k, v] for k, v in sorted(counts.items(), key=lambda x: -x[1])],
                   ["Class", "Modules"]))

lines.append(f"""
Python files parsed: **{C['counts']['python_parsed']}/{C['counts']['python_files']}** ·
parse errors: **{C['counts']['parse_errors']}** · Node files: **{C['counts']['node_files']}**

A zero parse-error tree matters independently: CLAUDE.md §11c requires a whole-tree
compile gate before any deploy, after autonomous annotation campaigns pushed 31 syntax
errors to `main`. This census parsed every tracked `.py` with `ast.parse` and found none.

""")

lines.append("## By top-level package\n")
allcls = ["DEPLOY-ENTRYPOINT", "ACTIVE-STATIC", "DEPLOYED-DEP", "SERVED-ASSET",
          "SCRIPT-REFERENCED", "DORMANT", "DEAD-CANDIDATE", "TEST"]
rows = []
for p in sorted(pkg, key=lambda k: -sum(pkg[k].values())):
    c = pkg[p]
    if sum(c.values()) < 3:
        continue
    rows.append([f"`{p}`", sum(c.values())] + [c.get(k, "") or "" for k in allcls])
lines.append(table(rows, ["Package", "Total"] + [k.replace("-", "&#8209;") for k in allcls]))

dead = {f: m for f, m in M.items() if m["classification"] == "DEAD-CANDIDATE"}
lines.append(f"\n## DEAD-CANDIDATE ({len(dead)}) — unreferenced, unserved, untested\n")
lines.append(
    "These have **two of three proofs** (static-unreferenced, test-untested). They are "
    "**not deletable** until the Phase 0.3 runtime window confirms they are unobserved, "
    "and then only through the quarantine ladder (tripwire → disable → delete).\n\n"
)
dead_by_dir = defaultdict(list)
for f, m in dead.items():
    dead_by_dir["/".join(f.split("/")[:2]) if "/" in f else "(root)"].append((f, m))
for d in sorted(dead_by_dir, key=lambda k: -sum(x[1]["loc"] for x in dead_by_dir[k])):
    items = sorted(dead_by_dir[d], key=lambda x: -x[1]["loc"])
    loc = sum(x[1]["loc"] for x in items)
    lines.append(f"\n### `{d}` — {len(items)} modules, {loc:,} LOC\n")
    rows = []
    for f, m in items:
        flags = []
        if m.get("has_main"):
            flags.append("`__main__`")
        if m.get("routes"):
            flags.append(f"{len(m['routes'])} routes")
        if m.get("loops"):
            flags.append(f"{len(m['loops'])} loops")
        rows.append([f"`{f}`", f"{m['loc']:,}", " ".join(flags) or "—"])
    lines.append(table(rows, ["Module", "LOC", "Contains"]))

dorm = {f: m for f, m in M.items() if m["classification"] == "DORMANT"}
lines.append(f"\n## DORMANT ({len(dorm)}) — reached only by tests\n")
lines.append(
    "A test is not a user. These are live enough to break CI but have no production "
    "caller; they are prime Phase 4 tripwire candidates *after* the runtime overlay.\n\n"
)
lines.append(table(
    [[f"`{f}`", f"{m['loc']:,}", m["n_importers_test"]]
     for f, m in sorted(dorm.items(), key=lambda x: -x[1]["loc"])],
    ["Module", "LOC", "Test importers"]))

eps = {f: m for f, m in M.items() if m["classification"] == "DEPLOY-ENTRYPOINT"}
lines.append(f"\n## DEPLOY-ENTRYPOINT ({len(eps)}) — what production actually starts\n")
lines.append(table(
    [[f"`{f}`", f"{m['loc']:,}", ", ".join(f"`{x}`" for x in m["entrypoint_refs"][:3])]
     for f, m in sorted(eps.items())],
    ["Module", "LOC", "Named by"]))

big = sorted(M.items(), key=lambda x: -x[1]["loc"])[:25]
lines.append("\n## 25 largest modules (surgical-risk surface)\n")
lines.append(table(
    [[f"`{f}`", f"{m['loc']:,}", m["classification"], m["n_importers_non_test"]]
     for f, m in big],
    ["Module", "LOC", "Class", "Non-test importers"]))

(OUT / "modules.md").write_text("\n".join(lines), encoding="utf-8")

# ------------------------------------------------------------------- routes.md
lines = [banner("routes.md — route census",
                "Every registered FastAPI and Express route, with its owner, its "
                "declaring module, and its router-level auth posture.")]

py_routes = []
for f, m in PYM.items():
    for r in m.get("routes", []):
        py_routes.append((f, m, r))
node_routes = []
for f, m in NODEM.items():
    for r in m.get("routes", []):
        node_routes.append((f, m, r))

lines.append(f"""## Totals

| Tier | Routes | Declaring modules |
|---|---|---|
| FastAPI (Python) | **{len(py_routes)}** | {len({f for f, _, _ in py_routes})} |
| Express (Node) | **{len(node_routes)}** | {len({f for f, _, _ in node_routes})} |
| **Total** | **{len(py_routes) + len(node_routes)}** | |

""")

by_file = defaultdict(list)
for f, m, r in py_routes:
    by_file[f].append(r)
lines.append("## FastAPI routes by declaring module\n")
rows = []
for f in sorted(by_file, key=lambda k: -len(by_file[k])):
    m = PYM[f]
    prefix = m.get("router_prefix") or "—"
    auth = "router-level `Depends(_router_auth_dep)`" if f.endswith(
        "routes/aria.py") else ("app-level — **verify per route**" if f.endswith(
            "main.py") else "—")
    rows.append([f"`{f}`", len(by_file[f]), f"`{prefix}`", auth])
lines.append(table(rows, ["Module", "Routes", "Router prefix", "Auth posture"]))

lines.append("""
> **Auth posture is reported, not audited.** `routes/aria.py:292` declares
> `APIRouter(..., dependencies=[Depends(_router_auth_dep)])`, so every route it
> registers inherits that gate. Routes registered directly on `app` in `main.py`
> inherit nothing and must each be checked — `GET /phase/gates` is documented in
> CLAUDE.md §1 as deliberately unauthenticated. Per-route dependency analysis is
> **not** in this census and is required before the Phase 5 provider-call audit.

""")

# collisions
seen = defaultdict(list)
for f, m, r in py_routes:
    # Test files register duplicates ON PURPOSE to exercise the R-F2278 guard;
    # counting them reports a defect that does not exist in production.
    if r.get("path") and not PYM[f]["is_test"]:
        prefix = PYM[f].get("router_prefix") or ""
        key = (r["decorator"].upper(), prefix + r["path"])
        seen[key].append((f, r["handler"], r["line"]))
coll = {k: v for k, v in seen.items() if len(v) > 1}
lines.append(f"## Duplicate FastAPI registrations ({len(coll)}, production only)\n")
lines.append(
    "Test modules are excluded: `aria_service/tests/test_rf2278_no_duplicate_routes.py` "
    "registers `GET /dup` and `GET /boot-dup` twice **by design**, to prove the "
    "R-F2278 duplicate-route guard fires. Counting those reports a defect that does "
    "not exist.\n\n"
)
if coll:
    lines.append(
        "Same method+path registered more than once. In FastAPI the **first** "
        "registration wins, so the later handler is unreachable. Each of these is "
        "either a defect or a deliberate override that must be documented.\n\n"
    )
    rows = []
    for (meth, path), regs in sorted(coll.items())[:60]:
        rows.append([f"`{meth} {path}`", len(regs),
                     "<br>".join(f"`{f}:{ln}` {h}()" for f, h, ln in regs[:4])])
    lines.append(table(rows, ["Route", "Registrations", "Declared at"]))
else:
    lines.append("None found.\n")

nby = defaultdict(list)
for f, m, r in node_routes:
    nby[f].append(r)
lines.append("\n## Express routes by declaring module (top 25)\n")
lines.append(table(
    [[f"`{f}`", len(nby[f]), NODEM[f]["classification"]]
     for f in sorted(nby, key=lambda k: -len(nby[k]))[:25]],
    ["Module", "Routes", "Class"]))

(OUT / "routes.md").write_text("\n".join(lines), encoding="utf-8")

# -------------------------------------------------------------------- loops.md
lines = [banner("loops.md — background loop census",
                "Every `while True` loop, task spawn and timer, with the lease / "
                "singleton / restart-safety evidence the census can see.")]

loops = [(f, m, lp) for f, m in PYM.items() for lp in m.get("loops", [])]
spawns = [(f, m, sp) for f, m in PYM.items() for sp in m.get("spawns", [])]
timers = [(f, m, t) for f, m in NODEM.items() for t in m.get("timers", [])]
singleton = [s for s in spawns if s[2]["spawner"] == "_singleton_task"]

lines.append(f"""## Totals

| Construct | Count | Modules |
|---|---|---|
| `while True` loops (Python) | **{len(loops)}** | {len({f for f, _, _ in loops})} |
| Task spawns (Python) | **{len(spawns)}** | {len({f for f, _, _ in spawns})} |
| &nbsp;&nbsp;of which `_singleton_task` | **{len(singleton)}** | {len({f for f, _, _ in singleton})} |
| Timers (`setInterval`/`setTimeout`/cron, Node) | **{len(timers)}** | {len({f for f, _, _ in timers})} |

`_singleton_task` is the R-F2073 singleton-lock wrapper. CLAUDE.md §1 records that
R-F2668 had to add `respawn=False` for one-shots, because respawn-registering a
one-shot made its **normal completion look like a death** — it was re-spawned 5x and
the resulting ERROR reset the gate-#3 clean-day streak every boot. Spawns that are
*not* routed through `_singleton_task` have no such lock and are listed below.

""")

nosleep = [(f, lp) for f, m, lp in loops if not lp["sleeps"]]
lines.append(f"## `while True` loops without an observed `sleep` ({len(nosleep)})\n")
lines.append(
    "A forever-loop with no awaited sleep on some path is the event-loop-wedge class "
    "CLAUDE.md §16 already records two flaky tests for. This is a **static** read: a "
    "sleep may sit in a callee the census cannot follow. Treat as leads, not verdicts.\n\n"
)
lines.append(table(
    [[f"`{f}:{lp['line']}`", f"`{lp['enclosing']}()`"] for f, lp in nosleep[:40]],
    ["Location", "Enclosing"]) if nosleep else "None found.\n")

byf = Counter(f for f, _, _ in loops)
lines.append("\n## Modules with the most forever-loops\n")
lines.append(table(
    [[f"`{f}`", n, PYM[f]["classification"]] for f, n in byf.most_common(20)],
    ["Module", "Loops", "Class"]))

sp_by = Counter(f for f, _, _ in spawns)
lines.append("\n## Modules with the most task spawns\n")
lines.append(table(
    [[f"`{f}`", n,
      sum(1 for s in spawns if s[0] == f and s[2]["spawner"] == "_singleton_task"),
      PYM[f]["classification"]]
     for f, n in sp_by.most_common(20)],
    ["Module", "Spawns", "via `_singleton_task`", "Class"]))

lines.append("\n## Node timers\n")
tby = Counter(f for f, _, _ in timers)
lines.append(table(
    [[f"`{f}`", n, NODEM[f]["classification"]] for f, n in tby.most_common(20)],
    ["Module", "Timers", "Class"]))

(OUT / "loops.md").write_text("\n".join(lines), encoding="utf-8")

# ------------------------------------------------------------------- stores.md
lines = [banner("stores.md — state store census",
                "Every Redis key-family, SQLite file, volume path and data file the "
                "code references, with the modules that touch it.")]

keyfam = defaultdict(set)
for f, m in M.items():
    for k in m.get("redis_keys", []):
        keyfam[k].add(f)
vols = defaultdict(set)
for f, m in PYM.items():
    for v in m.get("volumes", []):
        vols[v].add(f)
files_touched = defaultdict(set)
for f, m in PYM.items():
    for v in m.get("files_touched", []):
        files_touched[v].add(f)
sqlite_mods = {f: m["sqlite_calls"] for f, m in PYM.items() if m.get("sqlite_calls")}

lines.append(f"""## Totals

| Kind | Distinct | Referencing modules |
|---|---|---|
| Redis/state key families (`crucix:<ns>:<name>`) | **{len(keyfam)}** | {len({f for s in keyfam.values() for f in s})} |
| Volume paths (`/data`, `/mnt`, `/var`) | **{len(vols)}** | {len({f for s in vols.values() for f in s})} |
| `.db`/`.sqlite`/`.json`/`.jsonl` literals | **{len(files_touched)}** | {len({f for s in files_touched.values() for f in s})} |
| Modules calling `sqlite3.connect` | **{len(sqlite_mods)}** | |

**Owner rule.** A key family with exactly one referencing module has a clear owner.
One with many has *shared* ownership and is a Phase 4.3 hazard: the protocol forbids
`rm` on orphan stores — archive with a manifest, then remove the code path.

**This census cannot prove a store is orphaned.** It sees *references in code*, not
*keys in production*. A family that exists live but is written by no tracked module is
exactly the CLAUDE.md §1 gate-#4 failure — `crucix:aria:dd:quarantined` had **no writer
anywhere in the tree** yet gated a Phase A exit criterion for months. Detecting that
class requires a live key-space scan, which is Phase 0.3 work.

""")

shared = {k: v for k, v in keyfam.items() if len(v) >= 4}
lines.append(f"## Shared key families — 4+ referencing modules ({len(shared)})\n")
lines.append(table(
    [[f"`{k}`", len(v), "<br>".join(f"`{x}`" for x in sorted(v)[:3])]
     for k, v in sorted(shared.items(), key=lambda x: -len(x[1]))[:40]],
    ["Key family", "Modules", "Sample referencing modules"]))

solo = {k: v for k, v in keyfam.items() if len(v) == 1}
lines.append(f"\n## Single-owner key families ({len(solo)})\n")
lines.append(table(
    [[f"`{k}`", f"`{list(v)[0]}`"] for k, v in sorted(solo.items())[:60]],
    ["Key family", "Owner"]))

lines.append(f"\n## Volume paths ({len(vols)})\n")
lines.append(table(
    [[f"`{v}`", len(s), "<br>".join(f"`{x}`" for x in sorted(s)[:3])]
     for v, s in sorted(vols.items())][:40],
    ["Path", "Modules", "Referenced by"]))

lines.append(f"\n## Modules calling `sqlite3.connect` ({len(sqlite_mods)})\n")
lines.append(table(
    [[f"`{f}`", len(cs), ", ".join(str(c["line"]) for c in cs[:6])]
     for f, cs in sorted(sqlite_mods.items(), key=lambda x: -len(x[1]))[:30]],
    ["Module", "Calls", "Lines"]))

(OUT / "stores.md").write_text("\n".join(lines), encoding="utf-8")

print("wrote modules.md routes.md loops.md stores.md")
print("  DEAD-CANDIDATE:", len(dead), " DORMANT:", len(dorm), " ENTRYPOINT:", len(eps))
print("  py_routes:", len(py_routes), " node_routes:", len(node_routes),
      " collisions:", len(coll))
print("  loops:", len(loops), " spawns:", len(spawns), " singleton:", len(singleton),
      " no-sleep loops:", len(nosleep))
print("  key families:", len(keyfam), " volumes:", len(vols), " sqlite mods:", len(sqlite_mods))
