<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="ADD_IUID_INDICATOR_TO_NMCRL"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:Types="http://eportal.nspa.nato.int/Types"
           targetNamespace="http://eportal.nspa.nato.int/Action">

  <xs:import namespace="http://eportal.nspa.nato.int/Types" schemaLocation="DataTypes.xsd"/>
  
  <xs:complexType name="ADD_IUID_INDICATOR_TO_NMCRL">
    <xs:sequence>      
      <!--Specific Data-->
      <xs:element name="PRIORITY_CODE_2867" type="Types:PRIORITY_CODE" minOccurs="1" maxOccurs="1"/>
    </xs:sequence>
    <xs:attribute name="ACTION_SERIAL_NUMBER_8725" type="Types:ACTION_SERIAL_NUMBER" use="required"/>
  </xs:complexType>
  
</xs:schema>