<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="SEND_RESPONSE"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"           
           xmlns:Types="http://eportal.nspa.nato.int/Types"
           xmlns:Collections="http://eportal.nspa.nato.int/Collections"
           targetNamespace="http://eportal.nspa.nato.int/Action">

  <xs:import namespace="http://eportal.nspa.nato.int/Types" schemaLocation="DataTypes.xsd"/>
  <xs:import namespace="http://eportal.nspa.nato.int/Collections" schemaLocation="CollectionTypes.xsd"/>

  <xs:complexType name="SEND_RESPONSE">
    <xs:sequence>
		<xs:element name="COMMENT_8703" type="Types:COMMENT" minOccurs="0" maxOccurs="1"/>
		<xs:element name="ATTACHMENTS" type="Collections:ATTACHMENTS" minOccurs="0" maxOccurs="1"/>              
    </xs:sequence>
    <xs:attribute name="ACTION_SERIAL_NUMBER_8725" type="Types:ACTION_SERIAL_NUMBER" use="required"/>
    <xs:attribute name="COLLABORATION_ID_8721" type="Types:COLLABORATION_ID" use="required"/>
	<xs:attribute name="RETURN_CODE_8713" type="Types:RETURN_CODE" use="required"/>
  </xs:complexType>
  
</xs:schema>