// lib/aria/seed_knowledge.mjs
// Seeds ARIA's knowledge base with core defence industry facts
// Run once on first startup (checks if already seeded)

import { storeFact } from './knowledge.mjs';

const SEED_FACTS = [
  // Ammunition calibres & platforms
  ['30x113mm ammunition', 'Used in M230 Chain Gun (AH-64 Apache) and GAU-8/A Avenger (A-10). Primary manufacturers: General Dynamics OTS (USA), Northrop Grumman (USA), Nammo (Norway). ITAR-controlled. Variants: M789 HEDP, M799 HEI, PGU-13/B API.', 'CONFIRMED'],
  ['30x173mm ammunition', 'NATO standard for Mk44 Bushmaster II and GAU-22/A (F-35). Manufacturers: Nammo, Rheinmetall, General Dynamics, Northrop Grumman. Used in CV90, Stryker Dragoon, VBCI.', 'CONFIRMED'],
  ['12.7x99mm (.50 BMG)', 'NATO standard heavy machine gun round. Used in M2 Browning, M85. Manufacturers: FN Herstal, General Dynamics, Nammo, PMP (South Africa), CBC (Brazil).', 'CONFIRMED'],
  ['5.56x45mm NATO', 'Standard NATO rifle cartridge. Used in M4, HK416, FN SCAR, Galil. Produced by virtually all NATO ammunition manufacturers. Export generally unrestricted for allied nations.', 'CONFIRMED'],
  ['7.62x51mm NATO', 'Standard NATO medium machine gun/marksman cartridge. Used in FN MAG, M240, HK G3. Widely produced and exported.', 'CONFIRMED'],
  ['155mm artillery', 'NATO standard howitzer calibre. Key platforms: M777, PzH 2000, CAESAR, K9 Thunder, AS90. Manufacturers: Nammo, Rheinmetall, Nexter, General Dynamics, Elbit. Critical supply shortage globally since 2022.', 'CONFIRMED'],

  // Key OEMs and their African export track record
  ['Paramount Group', 'South African defence company. Products: Mbombe APC, Marauder, Matador. Export markets: Nigeria, Kenya, Mozambique, UAE, Jordan, Kazakhstan. Strong Africa presence, non-ITAR.', 'CONFIRMED'],
  ['Turkish Aerospace (TUSAS)', 'Turkish state defence company. Products: Hürjet trainer, Anka UAV, Atak helicopter. Active exports to: Nigeria, Pakistan, UAE. Aggressive pricing vs Western competitors.', 'CONFIRMED'],
  ['Baykar', 'Turkish drone manufacturer. Products: Bayraktar TB2, TB3, Akinci. Export markets: Ukraine, Nigeria, Ethiopia, Angola, Morocco, Pakistan, UAE. Game-changer in African drone procurement.', 'CONFIRMED'],
  ['Leonardo', 'Italian defence conglomerate. Products: M-346 trainer, AW109/AW139 helicopters, naval systems. 2026 deal: 24 M-346 to Nigeria (largest West African military aircraft acquisition).', 'CONFIRMED'],
  ['Embraer', 'Brazilian aerospace. Products: Super Tucano (A-29), KC-390. Export markets: Nigeria (24 Super Tucano), Angola, Mozambique, Portugal. Lusophone advantage.', 'CONFIRMED'],
  ['Damen', 'Dutch shipbuilder. Products: patrol vessels, corvettes, coast guard vessels. Active across African coast guards (Nigeria, Senegal, Mozambique). Non-ITAR.', 'CONFIRMED'],
  ['Elbit Systems', 'Israeli defence. Products: Hermes UAVs, surveillance systems, Sabrah light tanks. Active in Africa: Cameroon, Ethiopia, various. Export compliance varies by destination.', 'CONFIRMED'],
  ['Rheinmetall', 'German defence. Products: Lynx IFV, Fuchs APC, ammunition (30mm, 35mm, 120mm, 155mm), air defence. Active exports to SADC nations.', 'CONFIRMED'],
  ['Denel', 'South African state defence. Products: Rooivalk helicopter, ammunition (all calibres), Umkhonto SAM. Financial difficulties but deep African market knowledge.', 'CONFIRMED'],
  ['Nammo', 'Norwegian-Finnish ammunition manufacturer. Products: all NATO calibres including 30x113mm, 30x173mm, 155mm, shoulder-fired weapons (M72). Key NATO supplier.', 'CONFIRMED'],

  // Key markets — military structure
  ['Angola FAA', 'Forças Armadas Angolanas (Angolan Armed Forces). Branches: Army, Navy (Marinha de Guerra), Air Force (Força Aérea Nacional). Equipment: mix of Soviet-era and modern Western. Modernisation programme active. Key procurement authority: Ministério da Defesa Nacional.', 'CONFIRMED'],
  ['Mozambique FADM', 'Forças Armadas de Defesa de Moçambique. Active counter-insurgency in Cabo Delgado province (since 2017). Equipment needs: patrol vessels, ISR, infantry equipment. SADC and EU training missions active.', 'CONFIRMED'],
  ['Nigeria Armed Forces', 'Largest military in West Africa. Active counter-terrorism (Boko Haram/ISWAP in NE), counter-banditry (NW). Major procurement: Super Tucano (Brazil/USA), M-346 (Italy), patrol vessels (Damen). Key authority: Ministry of Defence, Abuja.', 'CONFIRMED'],
  ['Kenya Defence Forces', 'East African regional hub. Active in AMISOM/ATMIS (Somalia). Equipment: F-5 (retiring), helicopters (MD530, AH-1), armoured vehicles. Modernisation focus on ISR and border security.', 'CONFIRMED'],

  // Export control frameworks
  ['UK export controls', 'Managed by ECJU (Export Control Joint Unit). Licence types: SIEL (Standard Individual), OIEL (Open Individual), OGEL (Open General). Assessment criteria: Consolidated Criteria (human rights, regional stability, diversion risk). Processing time: 20-60 working days.', 'CONFIRMED'],
  ['ITAR overview', 'International Traffic in Arms Regulations (US). Covers USML (United States Munitions List) items. Requires DSP-5 license for export. Key risk: any product with >de minimis US content triggers ITAR. Managed by DDTC (Directorate of Defense Trade Controls).', 'CONFIRMED'],
  ['EU dual-use regulation', 'Regulation 2021/821. Covers items in Annex I (based on Wassenaar, MTCR, NSG, Australia Group). Catch-all provision (Art. 4) for non-listed items. Member states issue licences independently.', 'CONFIRMED'],

  // Arkmurus positioning
  ['Arkmurus business model', 'Defence brokering and advisory firm. Core competency: Lusophone Africa (Angola, Mozambique, Guinea-Bissau, Cape Verde, São Tomé, Brazil). Acts as intermediary between OEMs and end-user armed forces/MoDs. UK-based, export control compliant (UK/EU/US regulations). Products: armoured vehicles, UAVs, border security, ammunition, training, logistics.', 'CONFIRMED'],

  // Pricing benchmarks
  ['Armoured vehicles pricing', 'Protected vehicles (Paramount Mbombe/Marauder class): $500K-$1.2M per unit. 50-100 unit order: $80M-$120M total. Turkish alternatives (Otokar Cobra/FNSS Pars): 20-30% cheaper. Chinese (Norinco VN-1): 40-50% cheaper but less capable. Always factor 15-20% for spares package and training.', 'ASSESSED'],
  ['UAV system pricing', 'Bayraktar TB2 system (6 aircraft + GCS + logistics): ~$70M. Full programme with training: $80-120M. Chinese Wing Loong II: ~$1-2M per unit (significantly cheaper). Israeli Hermes 900: ~$10M per system. Training programme typically $5-15M additional.', 'ASSESSED'],
  ['Ammunition pricing', 'Small arms ammunition (5.56mm NATO): $0.30-0.50/round bulk. 12.7mm: $3-5/round. 30x113mm: $40-80/round depending on variant. 155mm: $3,000-8,000/round (precision guided up to $100K). Annual supply contracts typically $20-50M for medium military.', 'ASSESSED'],
  ['Patrol vessel pricing', '30-40m patrol vessel: $15-25M. 50-60m OPV: $40-80M. Fleet of 4 vessels + training + logistics: $150-250M. Damen builds in 18-24 months. Turkish alternatives (Dearsan, ADIK): 20-30% cheaper.', 'ASSESSED'],
  ['Training programme pricing', 'Infantry training (battalion, 6 months): $5-10M. Pilot training (12 students, fixed-wing): $15-25M. Counter-terrorism/special forces: $3-8M per package. Includes instructors, curriculum, equipment, consumables.', 'ASSESSED'],

  // Approach strategies by region
  ['Africa procurement approach', 'Key principles: (1) Relationships before contracts — invest in MoD engagement 12-18 months before tender. (2) Local partners are essential — identify a reputable local agent/representative. (3) Language matters — Lusophone markets strongly prefer Portuguese-speaking interlocutors. (4) Offset obligations are common — be prepared to propose technology transfer, local assembly, or training. (5) Payment terms — African procurement often uses letter of credit or deferred payment; factor financing into pricing.', 'CONFIRMED'],
  ['FMS process', 'US Foreign Military Sales: (1) Buyer submits Letter of Request (LOR) to US DSCA. (2) DSCA prepares Letter of Offer and Acceptance (LOA). (3) Congressional notification required for deals >$25M (major defence equipment). (4) Timeline: 6-18 months from LOR to contract. (5) Arkmurus role: advisory on LOR preparation, platform selection, integration planning. Cannot broker ITAR items directly without US export partner.', 'CONFIRMED'],
  ['Direct commercial sales approach', 'For non-ITAR equipment via DCS: (1) Identify requirement through MoD engagement or tender notice. (2) Match OEM product to requirement. (3) Obtain end-user certificate from buyer government. (4) Apply for export licence (UK SIEL, 20-60 working days). (5) Negotiate commercial terms (price, delivery, training, spares). (6) Arkmurus fee: typically 5-12% commission depending on deal size and complexity.', 'CONFIRMED'],

  // Geopolitical drivers
  ['Sahel instability', 'The Sahel region (Mali, Burkina Faso, Niger, Chad) has seen military coups since 2020, expulsion of French forces, and growing Russian Wagner/Africa Corps presence. Creates procurement opportunities: (1) Neighbouring countries (Nigeria, Ghana, Senegal, Côte d\'Ivoire) are bolstering border defences. (2) ECOWAS standby force needs equipment. (3) Russian replacement of French equipment opens new supplier windows.', 'CONFIRMED'],
  ['Indo-Pacific rearmament', 'Philippines, Indonesia, Vietnam, India are all in major military modernisation programmes driven by South China Sea tensions. Philippines Horizon 3 programme: $5B+ through 2028. Indonesia MEF (Minimum Essential Force): frigates, fighters, submarines. Vietnam: diversifying away from Russian equipment (opportunity for Western/Israeli alternatives).', 'CONFIRMED'],
  ['Post-Ukraine equipment replacement', 'European NATO countries are replenishing stocks donated to Ukraine. Poland: $30B+ programme (K2 tanks, FA-50 fighters, HIMARS). Romania, Bulgaria, Greece upgrading Soviet-era equipment to NATO standard. Creates secondary market for replaced equipment (older but functional) suitable for African buyers.', 'CONFIRMED'],

  // Defence exhibitions
  ['Key defence exhibitions', 'DSEI (London, Sep): Largest European defence show, Arkmurus home base. IDEX (Abu Dhabi, Feb): Middle East focus, major African buyer attendance. AAD (Pretoria, Sep, biennial): Africa\'s premier defence show. ShieldAfrica (Abidjan, Jan, biennial): West Africa focus. EUROSATORY (Paris, Jun, biennial): Land and airland defence. FIDAE (Santiago, Apr, biennial): Latin America. DSA (Kuala Lumpur, Apr, biennial): Southeast Asia.', 'CONFIRMED'],

  // Module 3: Budget cycle intelligence by market
  ['Angola defence budget cycle', 'Fiscal year: January-December. OGE (Orçamento Geral do Estado) submitted Q3 previous year. Defence allocation typically 3-4% of GDP. Oil revenue drives budget — Brent above $70 = healthy defence spending. Key procurement windows: Q1-Q2 after budget approval. Supplementary budgets possible mid-year if oil revenue exceeds projections.', 'ASSESSED'],
  ['Mozambique defence budget cycle', 'Fiscal year: January-December. Budget submitted to parliament Q4. Defence spending constrained by Cabo Delgado insurgency costs. EU/SADC contributions supplement national budget. Key procurement: Q1-Q2. Emergency procurement for counter-insurgency can bypass normal cycle.', 'ASSESSED'],
  ['Nigeria defence budget cycle', 'Fiscal year: January-December. Budget typically delayed 2-3 months. Defence gets ~6-8% of total budget. Three service budgets (Army, Navy, Air Force) plus MoD central. Capital vs recurrent split important — equipment falls under capital. Key windows: Q2-Q3 after budget passage.', 'ASSESSED'],
  ['Kenya defence budget cycle', 'Fiscal year: July-June. Budget read June. KDF allocation steady at ~1.2% GDP. AMISOM/ATMIS reimbursements create separate equipment funding. Tender process relatively transparent. Key windows: Q1 (Jul-Sep) after budget approval.', 'ASSESSED'],
  ['Brazil defence budget cycle', 'Fiscal year: January-December. Largest military in Latin America. LBDN (Livro Branco) sets 20-year strategy. PAED (Strategic Programme) drives major procurement. Budget approved December. Key windows: Q1-Q2. Multi-year appropriations for major platforms (Gripen, PROSUB).', 'ASSESSED'],
  ['Indonesia defence budget cycle', 'Fiscal year: January-December. MEF (Minimum Essential Force) programme drives procurement through 2029. Budget approved October. Defence allocation ~0.7% GDP (target 1.5%). Key procurement: Q1-Q3. Offset requirements 35-85% depending on contract value.', 'ASSESSED'],
  ['Philippines defence budget cycle', 'Fiscal year: January-December. Horizon 3 modernisation programme (2023-2028). NDRRMC supplementary funding for disaster response. Budget approved December. Key procurement: Q1-Q2. US FMS significant channel alongside domestic procurement.', 'ASSESSED'],
  ['UAE defence budget cycle', 'Fiscal year: January-December. No public budget constraint — oil-funded sovereign wealth. EDGE Group is procurement/industrial champion. Procurement continuous year-round. IDEX (February) is primary deal-making venue. Offset programme (Tawazun) requires 60% local content.', 'ASSESSED'],

  // ── PLATFORM-TO-EQUIPMENT MAPPING (critical for "if they buy X, they need Y") ──
  ['AH-64 Apache equipment needs', 'Platform: AH-64 Apache attack helicopter. Ammunition: 30x113mm (M789 HEDP, M799 HEI via M230 chain gun), Hellfire missiles (AGM-114), Hydra 70mm rockets. Spare parts: T700-GE-701D engines, TADS/PNVS sensor heads, APU. Training: ~$15M for 12 pilots. Annual sustainment: ~$8-12M per squadron. ITAR-controlled — FMS only.', 'CONFIRMED'],
  ['Super Tucano A-29 equipment needs', 'Platform: Embraer A-29 Super Tucano. Ammunition: 12.7mm (.50 cal), Mk 81/82 bombs, 70mm rockets, AIM-9 Sidewinder optional. Low operating cost (~$1000/flight hour). Users: Nigeria (24), Angola, Mozambique, Afghanistan, Lebanon. Training: integrated in delivery. Lusophone advantage — Brazilian manufacturer, Portuguese documentation.', 'CONFIRMED'],
  ['M-346 Master equipment needs', 'Platform: Leonardo M-346 advanced jet trainer. Ammunition: training pods, optional 12.7mm gun pod, practice bombs. Nigeria ordering 24 units (2026, largest West Africa military aircraft buy). Can operate as light attack. Italian export — non-ITAR. Sustainment: ~$5M/year per squadron.', 'CONFIRMED'],
  ['Bayraktar TB2 equipment needs', 'Platform: Baykar TB2 UCAV. Weapons: MAM-L/MAM-C smart munitions (Roketsan). Ground control station + satellite link. Operational ceiling: 27,000ft, 27hr endurance. Export price: ~$5M per aircraft, full system (6 aircraft + GCS): ~$70M. Users: Ukraine, Nigeria, Ethiopia, Angola, Morocco, UAE. Non-ITAR. Training: 3-6 months.', 'CONFIRMED'],
  ['Lynx IFV equipment needs', 'Platform: Rheinmetall Lynx KF41 IFV. Ammunition: 30x173mm (Lance turret), 7.62mm coax. Crew: 3+8. Weight: 44t. German export — non-ITAR but German export restrictions can apply. Hungary ordered 218 units at ~$5.5M each. Active Iron Fist APS option.', 'CONFIRMED'],
  ['Patrol vessel equipment needs', 'Generic 30-50m patrol vessel. Weapons: 30mm naval cannon (Bushmaster), 12.7mm RWS, small arms. Systems: navigation radar, EO/IR sensor, communications suite. Crew: 15-30. Builders: Damen (NL), OCEA (FR), Dearsan (TR). Typical package: 4 vessels + training + 5yr spares = $100-200M.', 'ASSESSED'],

  // ── COUNTRY MILITARY STRUCTURES (expanded) ──
  ['Ghana Armed Forces', 'GAF: Army, Navy, Air Force. ~15,000 active. Participates in ECOWAS standby force and UN peacekeeping. Equipment ageing, modernisation needed. Key needs: APCs, patrol vessels, small arms. Procurement: Ministry of Defence, Burma Camp Accra. English-speaking, formal tender.', 'CONFIRMED'],
  ['Senegal Armed Forces', 'Forces armées sénégalaises. ~19,000 active. French-trained, strong ECOWAS contributor. Active in Casamance and Sahel. Key needs: vehicles, helicopters, ISR. Procurement: Ministère des Forces Armées, Dakar. FRENCH language essential. Former French colony — Nexter/Airbus historically strong.', 'CONFIRMED'],
  ['Ethiopia National Defense Force', 'ENDF: ~140,000 active (post-Tigray). Major reconstruction after 2020-2022 civil war. Previously Russian-equipped (Su-27, Mi-35). Diversifying to Turkish (Bayraktar) and Chinese. Key needs: everything — vehicles, aircraft, ammunition, training. Budget recovering. Addis Ababa procurement.', 'CONFIRMED'],
  ['Indonesia TNI structure', 'Tentara Nasional Indonesia: Army (TNI-AD), Navy (TNI-AL), Air Force (TNI-AU). ~400,000 active. MEF (Minimum Essential Force) programme through 2029. Major buys: Rafale (France), Scorpène submarines, K2 tanks (South Korea). Offset required: 35-85%. Ministry of Defence Jakarta. Indonesian + English.', 'CONFIRMED'],
  ['Philippines AFP structure', 'Armed Forces of Philippines: Army (PA), Navy (PN), Air Force (PAF). ~150,000 active. Horizon 3 modernisation (2023-2028, $5B+). Needs: frigates, fighters, helicopters, ISR. US FMS dominant but diversifying (South Korea, Israel). Camp Aguinaldo, Quezon City. English-speaking.', 'CONFIRMED'],
  ['Saudi Arabia military structure', 'RSLF + SANG (Saudi Arabian National Guard) + Royal Saudi Air Force. Combined ~250,000. Vision 2030 localisation through GAMI (General Authority for Military Industries). Biggest defence spender in Middle East (~$55B/year). Agent mandatory. Very formal, very slow (2-5 year cycles). Arabic + English. GAMI is procurement gatekeeper.', 'CONFIRMED'],

  // ── END-USER CERTIFICATE WORKFLOWS ──
  ['EUC Angola process', 'End-User Certificate for Angola: (1) Arkmurus drafts EUC template, (2) Submit to Ministério da Defesa Nacional via Defence Attaché or direct MoD contact, (3) MoD reviews and signs (typically signed by Vice-Minister or Director of Equipment), (4) Original posted to Arkmurus UK, (5) Submit with UK SIEL application to ECJU. Timeline: 4-8 weeks for MoD signature. Portuguese language. Include: item description, quantity, end-use statement, non-re-export clause.', 'ASSESSED'],
  ['EUC Nigeria process', 'End-User Certificate for Nigeria: (1) Prepare certificate per UK ECJU template, (2) Submit to Federal Ministry of Defence, Ship House Abuja, (3) Requires Permanent Secretary or Minister signature, (4) Can take 6-12 weeks due to bureaucracy, (5) Expedite via Defence Attaché (British High Commission Abuja). English language. Nigeria requires National Security Adviser (NSA) clearance for major deals.', 'ASSESSED'],
  ['UK SIEL application process', 'Standard Individual Export Licence (SIEL): (1) Register on SPIRE system (spire.trade.gov.uk), (2) Complete F680 pre-application for sensitive destinations, (3) Submit SIEL with: goods description, ECCN classification, end-user details, EUC, (4) ECJU assessment (20-60 working days), (5) May request additional information or conditions. Refusal grounds: Consolidated Criteria (human rights, regional stability, diversion risk). Appeal possible to Export Control Organisation.', 'CONFIRMED'],

  // ── FINANCIAL MODELLING ──
  ['Defence deal economics', 'Typical Arkmurus deal structure: (1) Base equipment cost (OEM price), (2) Training package (5-15% of equipment cost), (3) Spares & maintenance (10-20% initial, then annual), (4) Logistics/shipping (3-8% depending on destination), (5) Offset obligation (0-85% depending on country), (6) Arkmurus commission (5-12% of total deal value). Example: 50 APCs at $800K = $40M base + $4M training + $6M spares + $2M logistics = $52M total. Commission at 8% = $4.16M.', 'ASSESSED'],
  ['FMS financing terms', 'US Foreign Military Sales financing: (1) Cash sales (immediate payment), (2) FMF (Foreign Military Financing — US government grant, mainly for allies like Israel, Egypt, Jordan), (3) Commercial financing via US EXIM Bank (loan guarantee, 7-10 year terms, LIBOR+2-3%), (4) Direct commercial credit from OEM (rare, typically 2-3 year terms). For non-FMF recipients: budget constraints mean concessional financing critical. AfDB/EU Peace Facility can supplement.', 'ASSESSED'],
  ['Offset obligation guide', 'Offset requirements by market: UAE (Tawazun): 60% of contract value. Saudi Arabia (GAMI): 50-60% by 2030. Indonesia: 35-85% depending on contract value (>$10M = 85%). South Africa: 30-50% via DIPA. Brazil: varies, typically 100% for Gripen. Most African markets: 0-20% formal offset, but informal local content expectations (training, assembly, tech transfer). Offset types: direct (related to contract), indirect (investment in other sectors), technology transfer.', 'ASSESSED'],

  // ── SUPPLY CHAIN INTELLIGENCE ──
  ['Defence supply chain lead times', 'Typical lead times from order to delivery: Armoured vehicles: 12-24 months. UAV systems: 8-18 months. Ammunition (bulk): 6-12 months (longer for specialty calibres). Patrol vessels: 18-36 months (custom build). Helicopters: 18-30 months. Radar/air defence: 12-24 months. Training programmes: 3-6 months setup. Small arms: 3-6 months. Critical: ammunition supply chains globally strained since 2022 (Ukraine conflict). 155mm artillery shell backlog: 2-3 years.', 'ASSESSED'],
  ['Key component suppliers', 'Critical defence supply chain nodes: Engines — GE Aviation (US, ITAR), Rolls-Royce (UK), Safran (FR), Honeywell (US, ITAR). Fire control — Elbit (IL), Thales (FR), Leonardo (IT). Ammunition propellant — Nammo (NO), Rheinmetall (DE), General Dynamics (US, ITAR). Optics/EO — FLIR/Teledyne (US, ITAR), Thales (FR), Hensoldt (DE). Communications — L3Harris (US, ITAR), Thales (FR), Elbit (IL). ITAR components create cascading export restrictions on entire platforms.', 'CONFIRMED'],

  // ── MULTI-JURISDICTION COMPLIANCE (global scope) ──
  ['EU Common Position on arms exports', 'EU Council Common Position 2008/944/CFSP defines 8 criteria for arms export decisions. Each EU member state assesses independently. Key criteria: (1) International obligations/embargoes, (2) Human rights, (3) Internal tensions/armed conflict, (4) Regional stability, (5) National security of buyer + allies, (6) Buyer government behaviour, (7) Diversion risk, (8) Economic capacity. German exports most restrictive (Bundessicherheitsrat). French/Italian more permissive. Relevant for any European OEM product.', 'CONFIRMED'],
  ['US State Dept DSP-5 licence', 'Direct Commercial Sales licence for USML items. Required for ANY item on the US Munitions List exported from the US or containing US-origin components. Process: (1) Register with DDTC, (2) Submit DSP-5 application via D-Trade, (3) Congressional notification if >$25M (major equipment), >$7M (defence articles), or >$1M (firearms/ammunition), (4) Processing: 30-60 days typical, can extend to 6+ months for sensitive destinations. De minimis rule: >$0 of US-origin content = ITAR applies.', 'CONFIRMED'],
  ['Brazil offset requirements', 'Brazilian Industrial Compensation Policy (PCI): contracts >R$50M (~$10M) require offset. Typically 100% of contract value for major platforms. Types: co-production, technology transfer, direct procurement from Brazilian industry. Managed by CMID (Comissão Mista da Indústria de Defesa). Recent example: Gripen programme — Saab agreed to full technology transfer to Embraer. Arkmurus angle: leverage Lusophone advantage to navigate Brazilian offset bureaucracy.', 'CONFIRMED'],
  ['South Korea defence export growth', 'South Korea emerged as top-5 global arms exporter since 2022. Products: K2 Black Panther tank (Poland, Egypt), K9 Thunder howitzer (Poland, Estonia, Norway, Australia), FA-50 fighter (Poland, Iraq, Philippines), KSS-III submarine (Indonesia). Pricing: 15-25% below Western competitors, proven NATO-grade quality. Strategy: aggressive financing, rapid delivery, technology transfer. Key competitor for Arkmurus in Southeast Asia and Eastern Europe.', 'CONFIRMED'],

  // Competitive positioning insights
  ['Turkish defence export strategy', 'Turkey has become Africa\'s fastest-growing defence supplier since 2019. Strategy: (1) Government-to-government deals backed by presidential visits, (2) 20-30% below Western pricing, (3) Combat-proven systems (TB2 in Libya, Ethiopia), (4) No political conditions attached, (5) Fast delivery timelines. Counter: Emphasise lifecycle cost (Turkish spares expensive long-term), NATO interoperability issues, and Arkmurus advisory value-add.', 'CONFIRMED'],
  ['Chinese defence export strategy', 'China offers 40-50% below Western pricing with state-backed financing (often tied to BRI infrastructure). Products: VN-series APCs, Wing Loong UAVs, JF-17 fighters (with Pakistan). Weakness: After-sales support poor, interoperability limited, quality perception issues. Counter: Emphasise quality, training packages, lifecycle support, and Western interoperability.', 'CONFIRMED'],
  ['Russian equipment replacement opportunity', 'Russia\'s invasion of Ukraine (2022) triggered Western sanctions making spares/ammunition supply impossible for Russian-equipped African militaries. Angola (Su-30, Mi-17), Mozambique (Mi-24), Nigeria (Mi-35), Uganda (Su-30) all affected. This creates replacement windows for Western/Turkish/Israeli alternatives. Key approach: offer trade-in/phase-out programmes with guaranteed support contracts.', 'CONFIRMED'],
];

let _seeded = false;

export function seedKnowledgeBase() {
  if (_seeded) return;
  _seeded = true;
  let count = 0;
  for (const [topic, content, confidence] of SEED_FACTS) {
    storeFact(topic, content, 'seed', confidence);
    count++;
  }
  console.log(`[ARIA KB] Seeded ${count} core defence industry facts`);
}
