"""R-F3738 — CAPABILITY: the undici override floor must exclude the vulnerable range.

C-11 measured undici at HIGH with the fix available without a major bump. npm
audit reported FIVE advisories against the installed 7.28.0, not the two the
defect register lists:

  GHSA-8xcm-r25x-g524  downstream response desynchronisation via retry interceptor
  GHSA-4cwx-7wf7-3272  cross-user info disclosure / parse crash via cache directives
  GHSA-m8rv-5g2x-5cg5  CRLF injection via blob-like body `type`
  GHSA-jr45-8vmc-qm54  cross-user info disclosure via whitespace in Cache-Control
  GHSA-v3r7-h72x-cjcm  cookie attribute injection via unsanitised domain

Vulnerable range 7.0.0–7.28.0; all five fixed in 7.29.0.

WHY A FLOOR AND NOT A LOCKFILE REFRESH. The register says the override "pins it
to the vulnerable ^7.24.4". That is not quite right — `^7.24.4` PERMITS 7.29.0;
the lockfile had merely resolved to 7.28.0. So refreshing the lock alone would
have fixed today's tree while leaving the vulnerable range satisfiable, and any
future resolution could land back inside it silently. Raising the FLOOR makes
7.0.0–7.28.0 unsatisfiable by construction.

This test guards the floor, not the lockfile: a lockfile can be regenerated by
anyone, but lowering the declared floor is a deliberate act that should fail CI.

Run: python -m pytest aria_service/tests/test_rf3738_undici_floor.py -v
"""
from __future__ import annotations

import json
import re

from ._source_probe import repo_path

#: Highest version still carrying the five advisories.
LAST_VULNERABLE = (7, 28, 0)
FIXED_IN = (7, 29, 0)


def _parse(spec: str) -> tuple[int, int, int]:
    m = re.search(r"(\d+)\.(\d+)\.(\d+)", spec)
    assert m, f"cannot parse a version out of {spec!r}"
    return tuple(int(g) for g in m.groups())  # type: ignore[return-value]


def _pkg() -> dict:
    return json.loads(repo_path("package.json").read_text(encoding="utf-8"))


def test_the_override_floor_excludes_every_vulnerable_undici():
    spec = (_pkg().get("overrides") or {}).get("undici")
    assert spec, "the undici override disappeared — it is what controls transitive resolution"
    floor = _parse(spec)
    assert floor >= FIXED_IN, (
        f"undici override floor is {spec!r}; 7.0.0-{'.'.join(map(str, LAST_VULNERABLE))} "
        f"carries 5 HIGH advisories (GHSA-8xcm-r25x-g524 and four others). "
        f"Do not lower this below {'.'.join(map(str, FIXED_IN))}."
    )


def test_the_lockfile_actually_resolved_a_fixed_undici():
    """The floor is the rule; this is the evidence it took effect."""
    lock = json.loads(repo_path("package-lock.json").read_text(encoding="utf-8"))
    versions = [
        v.get("version")
        for k, v in (lock.get("packages") or {}).items()
        if k.endswith("node_modules/undici") and v.get("version")
    ]
    assert versions, "no undici entry in the lockfile"
    for v in versions:
        assert _parse(v) >= FIXED_IN, (
            f"lockfile resolved undici {v}, inside the vulnerable range — "
            f"run `npm install --package-lock-only` after changing the floor"
        )


def test_undici_is_still_only_a_transitive_dependency():
    """If it becomes a DIRECT import, the exposure changes and this needs re-review.

    Nothing in the tree imports undici today, which is why a floor bump carries
    no behavioural risk. A direct dependency would make that judgement stale.
    """
    pkg = _pkg()
    assert "undici" not in (pkg.get("dependencies") or {}), (
        "undici became a direct dependency — re-assess the upgrade's blast radius "
        "rather than relying on 'transitive, no usage'"
    )
