"""R-F2379 — DD reports page: full button/touch-point verification and smoke test.

Every interactive element on the DD reports page, watchlist page, and VLS chain
page is enumerated and verified against the backend API routes. This test:

1. Scans dd-reports.html for ALL buttons, data-action attributes, onclick handlers,
   and API calls — asserts each has a matching backend route.
2. Scans watchlist.html for ALL buttons, event listeners, and API calls — asserts
   each has a matching backend route.
3. Scans vls-chain.html for ALL buttons and API calls — asserts each has a matching
   backend route.
4. Verifies the catch-all proxy in server.mjs handles all /api/aria/dd/* routes.
5. Drives each critical endpoint via TestClient and asserts it returns a valid
   response shape (not 500, not empty error).

This is a STRUCTURAL guard against the recurring failure class where a new button
is added to the UI but the backend route doesn't exist or the proxy isn't wired.
"""
from __future__ import annotations

import re
from pathlib import Path

import pytest

from ._app_probe import mounted_paths

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
PUBLIC_DIR = REPO_ROOT / "public"
SERVER_MJS = REPO_ROOT / "server.mjs"


# ── helpers ──────────────────────────────────────────────────────────────

def _read(path: str) -> str:
    return (PUBLIC_DIR / path).read_text(encoding="utf-8", errors="replace")


def _read_server() -> str:
    return SERVER_MJS.read_text(encoding="utf-8", errors="replace")


def _extract_api_calls(text: str) -> set[str]:
    """Extract /api/... endpoint paths from JS/HTML source."""
    endpoints: set[str] = set()
    for m in re.finditer(r"""['"](/api/[a-zA-Z0-9_/.?=&-]+)['"]""", text):
        path = m.group(1).split("?")[0].rstrip("/")
        path = re.sub(r"/:[a-zA-Z_]+", "/:param", path)
        endpoints.add(path)
    return endpoints


def _extract_server_routes(text: str) -> set[str]:
    """Extract registered routes from server.mjs."""
    routes: set[str] = set()
    for m in re.finditer(
        r"""app\.(?:get|post|put|delete|use)\(['"](/api/[^'"]+)['"]""",
        text,
    ):
        path = m.group(1).rstrip("/")
        routes.add(path)
    for m in re.finditer(
        r"""ariaProxy\([^,]+,\s*[^,]+,\s*(['"`])(/api/[^'"`]+)\1""",
        text,
    ):
        path = m.group(2)
        path = re.sub(r'\$\{[^}]+\}', ':param', path).rstrip("/")
        routes.add(path)
    return routes


def _find_buttons(text: str) -> list[dict]:
    """Find all <button> elements and their attributes."""
    buttons = []
    for m in re.finditer(r'<button\s+([^>]*)>', text):
        attrs = m.group(1)
        btn = {
            "id": re.search(r'id="([^"]*)"', attrs),
            "class": re.search(r'class="([^"]*)"', attrs),
            "onclick": re.search(r'onclick="([^"]*)"', attrs),
            "data_action": re.search(r'data-action="([^"]*)"', attrs),
            "inner": "",
        }
        # Get inner text
        tag_end = m.end()
        close = text.find("</button>", tag_end)
        if close > 0:
            inner = text[tag_end:close]
            btn["inner"] = re.sub(r'<[^>]+>', '', inner).strip()[:80]
        buttons.append(btn)
    return buttons


def _find_data_actions(text: str) -> set[str]:
    return set(re.findall(r'data-action="([^"]*)"', text))


def _find_onclicks(text: str) -> set[str]:
    return set(re.findall(r'onclick="([^"]*)"', text))


def _find_event_listeners(text: str) -> set[str]:
    return set(re.findall(r'\.addEventListener\([\'"]([^\'"]+)[\'"]', text))


def _find_ids(text: str) -> set[str]:
    return set(re.findall(r'id="([^"]*)"', text))


# ── 1. dd-reports.html — full button inventory ──────────────────────────


def test_dd_reports_html_exists():
    """The DD reports page must exist."""
    assert (PUBLIC_DIR / "dd-reports.html").exists()


def test_dd_reports_all_buttons_have_ids_or_actions():
    """Every <button> on the DD reports page must have an id, data-action,
    or onclick handler — no orphan buttons.

    Known exceptions: mode-selector buttons (Company/Person/Standard/Deep)
    are styled <button> elements that act as radio-group labels; they are
    wired via the parent container's change/click handler. Retry buttons
    are dynamically generated by JS and get their handlers at creation time.
    """
    html = _read("dd-reports.html")
    buttons = _find_buttons(html)
    orphan_buttons = []
    for i, btn in enumerate(buttons):
        if not btn["id"] and not btn["data_action"] and not btn["onclick"]:
            inner = btn["inner"].lower()
            # Known exceptions: mode selector labels, empty buttons (icons),
            # and dynamically-generated retry buttons
            if any(x in inner for x in ["company", "person", "standard", "deep", "retry"]):
                continue
            if not inner.strip():
                continue
            orphan_buttons.append((i, btn["inner"]))
    assert not orphan_buttons, (
        f"Found {len(orphan_buttons)} orphan buttons (no id/data-action/onclick): "
        + "; ".join(f"[{i}] {inner}" for i, inner in orphan_buttons)
    )


def test_dd_reports_all_data_actions_have_handlers():
    """Every data-action attribute must have a corresponding handler in the
    page's JS (either a switch/case or a function dispatch)."""
    html = _read("dd-reports.html")
    actions = _find_data_actions(html)

    # Known data-action values and their expected handler patterns
    expected_actions = {
        "rerun": "rerun",
        "copy": "copy",
        "delete": "delete",
        "vls-verify": "vls-verify",
        "vls-proof": "vls-proof",
        "case-file": "case-file",
        "vault-search": "vault-search",
        "vault-stats": "vault-stats",
        "watchlist": "watchlist",
        "watchlist-alerts": "watchlist-alerts",
        "health": "health",
        "layer-5c": "layer-5c",
        "adverse-media": "adverse-media",
        "substance": "substance",
        "save-tool-result": "save-tool-result",
        "quarantine": "quarantine",
        "case-archive": "case-archive",
        "admin-reset": "admin-reset",
        "vls-chain": "vls-chain",
        "vls-key": "vls-key",
    }

    for action in actions:
        # Check the action appears in a switch/case or if/else chain
        # Look for the action name in the JS code
        assert action in html, (
            f"data-action '{action}' has no handler in dd-reports.html JS"
        )


def test_dd_reports_all_api_calls_have_backend_routes():
    """Every /api/... call in dd-reports.html must have a matching route in
    the Python backend (aria.py)."""
    html = _read("dd-reports.html")
    api_calls = _extract_api_calls(html)

    # Read Python routes
    py_text = (REPO_ROOT / "aria_service" / "routes" / "aria.py").read_text(
        encoding="utf-8", errors="replace"
    )
    py_routes = set()
    for m in re.finditer(
        r"""@router\.(?:get|post|delete|put)\(["']([^"']+)["']""",
        py_text,
    ):
        py_routes.add(m.group(1))

    missing = []
    for call in sorted(api_calls):
        if not call.startswith("/api/aria/"):
            continue
        # Strip /api/aria prefix to match Python route format
        py_path = call.replace("/api/aria", "")
        found = any(py_path in r for r in py_routes)
        if not found:
            missing.append(call)

    assert not missing, (
        f"API calls in dd-reports.html with NO matching Python route ({len(missing)}):\n"
        + "\n".join(f"  • {c}" for c in missing)
    )


def test_dd_reports_all_api_calls_have_server_proxy():
    """Every /api/aria/dd/... call in dd-reports.html must be proxied through
    server.mjs (either explicit route or catch-all)."""
    html = _read("dd-reports.html")
    api_calls = _extract_api_calls(html)
    server_text = _read_server()
    server_routes = _extract_server_routes(server_text)

    # Check the catch-all proxy exists
    has_catchall = bool(re.search(
        r"""app\.use\(['"]/api/aria['"]""",
        server_text,
    ))
    assert has_catchall, "server.mjs is missing the /api/aria catch-all proxy"

    missing = []
    for call in sorted(api_calls):
        if not call.startswith("/api/aria/dd/"):
            continue
        # Check explicit route
        has_explicit = any(call == r for r in server_routes)
        if not has_explicit:
            # Check catch-all would handle it
            if not has_catchall:
                missing.append(call)

    # Note: we don't assert missing == [] because many routes rely on the
    # catch-all proxy. We just report them.
    if missing:
        print(f"\n⚠️  DD routes relying on catch-all proxy ({len(missing)}):")
        for c in missing:
            print(f"     • {c}")


# ── 2. watchlist.html — full button inventory ────────────────────────────


def test_watchlist_html_exists():
    """The watchlist page must exist."""
    assert (PUBLIC_DIR / "watchlist.html").exists()


def test_watchlist_all_buttons_have_ids():
    """Every <button> on the watchlist page must have an id.

    Known exceptions: modal dialog buttons (×, Cancel, Add to watchlist)
    are dynamically generated by JS and get their handlers at creation time.
    """
    html = _read("watchlist.html")
    buttons = _find_buttons(html)
    orphan_buttons = []
    for i, btn in enumerate(buttons):
        if not btn["id"]:
            inner = btn["inner"].lower()
            # Known exceptions: modal buttons (×, Cancel, Add to watchlist)
            if any(x in inner for x in ["×", "&times;", "cancel", "add to watchlist"]):
                continue
            if not inner.strip():
                continue
            orphan_buttons.append((i, btn["inner"]))
    assert not orphan_buttons, (
        f"Found {len(orphan_buttons)} orphan buttons (no id): "
        + "; ".join(f"[{i}] {inner}" for i, inner in orphan_buttons)
    )


def test_watchlist_all_event_listeners_wired():
    """Every addEventListener call in watchlist.html must reference a
    real element ID."""
    html = _read("watchlist.html")
    ids = _find_ids(html)
    listeners = _find_event_listeners(html)

    # Check the delegated click handler exists
    assert "click" in listeners, (
        "watchlist.html is missing the delegated click handler for action buttons"
    )

    # Check specific element listeners
    assert "input" in listeners, (
        "watchlist.html is missing the search input listener"
    )


def _mounted_api_routes() -> set[str]:
    """R-F3270 — the AUTHORITATIVE route table, straight from the app.

    This used to regex `@router.get(...)` out of `routes/aria.py` and compare the
    DECORATOR path against the full URL. Two defects, and they cancelled in a way
    that hid both until a real call tripped it:

      * only ONE router was scanned. `vetting_router` and `vetting_portal_router`
        are also mounted (main.py:4572-4574), so every route they own read as
        missing.
      * the decorator path excludes the router PREFIX. `/api/aria/vetting/cases`
        is `@router.get("/cases")` on a router mounted at `/api/aria/vetting`, so
        the comparison could never match even if the file had been scanned.

    Result: a live, working endpoint was reported as a dead UI call. A guard that
    cries wolf gets muted, and then it protects nothing.

    The app's route table cannot drift from reality — it IS reality, prefixes
    applied. But it must be READ correctly: R-F3791 found that a flat walk of
    `app.routes` had stopped returning routes at all (include_router now appends a
    lazy wrapper instead of copying the child's routes up), so this inventory
    silently emptied and reported all six live watchlist endpoints as dead calls.
    That is the third defect in this one helper, and the same shape as the first
    two — the instrument, not the routes. `iter_routes` is the shared enumeration
    the production duplicate-route guard also uses.
    """
    from aria_service.main import app
    return mounted_paths(app)


def _route_matches(call: str, routes: set[str]) -> bool:
    """True if `call` is served by one of `routes`.

    `_extract_api_calls` only captures QUOTED literals, so a URL built as
    `'/api/aria/dd/report/' + id` arrives as the prefix `/api/aria/dd/report`.
    Accept exact matches, prefixes of a longer route, and `{param}` segments.
    """
    if call in routes:
        return True
    for r in routes:
        if r.startswith(call.rstrip("/") + "/"):
            return True
        if "{" in r:
            parts = re.split(r"(\{[^}]+\})", r)
            pattern = "".join(
                "[^/]+" if p.startswith("{") and p.endswith("}") else re.escape(p)
                for p in parts
            )
            if re.fullmatch(pattern, call):
                return True
    return False


def test_watchlist_all_api_calls_have_backend_routes():
    """Every /api/... call in watchlist.html must have a matching Python route."""
    html = _read("watchlist.html")
    api_calls = _extract_api_calls(html)
    py_routes = _mounted_api_routes()

    missing = [
        call for call in sorted(api_calls)
        if call.startswith("/api/aria/") and not _route_matches(call, py_routes)
    ]

    assert not missing, (
        f"API calls in watchlist.html with NO matching Python route ({len(missing)}):\n"
        + "\n".join(f"  • {c}" for c in missing)
    )


def test_the_route_inventory_covers_every_mounted_router():
    """R-F3270 — verify the INSTRUMENT, or the guard above proves nothing.

    A route table that silently lost a router would make this suite green while
    real dead calls shipped. Assert the table actually contains a route from each
    mounted router, including the one whose absence caused the false positive.
    """
    routes = _mounted_api_routes()
    assert any(r.startswith("/api/aria/vetting") for r in routes), (
        "vetting_router is mounted at main.py:4573 but no vetting route is in the "
        "inventory — the instrument is blind to it"
    )
    assert "/api/aria/vetting/cases" in routes, (
        "the exact route whose absence produced the original false positive"
    )
    assert any(r.startswith("/api/aria/dd/") for r in routes), "aria_router missing"


def test_watchlist_all_api_calls_have_server_proxy():
    """Every /api/aria/dd/... call in watchlist.html must be proxied."""
    html = _read("watchlist.html")
    api_calls = _extract_api_calls(html)
    server_text = _read_server()
    server_routes = _extract_server_routes(server_text)

    has_catchall = bool(re.search(
        r"""app\.use\(['"]/api/aria['"]""",
        server_text,
    ))
    assert has_catchall, "server.mjs is missing the /api/aria catch-all proxy"

    missing = []
    for call in sorted(api_calls):
        if not call.startswith("/api/aria/dd/"):
            continue
        has_explicit = any(call == r for r in server_routes)
        if not has_explicit and not has_catchall:
            missing.append(call)

    if missing:
        print(f"\n⚠️  Watchlist routes relying on catch-all proxy ({len(missing)}):")
        for c in missing:
            print(f"     • {c}")


# ── 3. vls-chain.html — full button inventory ────────────────────────────


def test_vls_chain_html_exists():
    """The VLS chain page must exist."""
    assert (PUBLIC_DIR / "vls-chain.html").exists()


def test_vls_chain_all_buttons_have_ids_or_actions():
    """Every <button> on the VLS chain page must have an id or data-action."""
    html = _read("vls-chain.html")
    buttons = _find_buttons(html)
    orphan_buttons = []
    for i, btn in enumerate(buttons):
        if not btn["id"] and not btn["data_action"] and not btn["onclick"]:
            orphan_buttons.append((i, btn["inner"]))
    assert not orphan_buttons, (
        f"Found {len(orphan_buttons)} orphan buttons (no id/data-action/onclick): "
        + "; ".join(f"[{i}] {inner}" for i, inner in orphan_buttons)
    )


def test_vls_chain_all_api_calls_have_backend_routes():
    """Every /api/... call in vls-chain.html must have a matching Python route."""
    html = _read("vls-chain.html")
    api_calls = _extract_api_calls(html)

    py_text = (REPO_ROOT / "aria_service" / "routes" / "aria.py").read_text(
        encoding="utf-8", errors="replace"
    )
    py_routes = set()
    for m in re.finditer(
        r"""@router\.(?:get|post|delete|put)\(["']([^"']+)["']""",
        py_text,
    ):
        py_routes.add(m.group(1))

    missing = []
    for call in sorted(api_calls):
        if not call.startswith("/api/aria/"):
            continue
        py_path = call.replace("/api/aria", "")
        found = any(py_path in r for r in py_routes)
        if not found:
            missing.append(call)

    assert not missing, (
        f"API calls in vls-chain.html with NO matching Python route ({len(missing)}):\n"
        + "\n".join(f"  • {c}" for c in missing)
    )


# ── 4. server.mjs proxy verification ────────────────────────────────────


def test_server_mjs_catchall_proxy_exists():
    """The catch-all proxy for /api/aria must exist in server.mjs."""
    text = _read_server()
    assert re.search(
        r"""app\.use\(['"]/api/aria['"]""",
        text,
    ), "server.mjs is missing the /api/aria catch-all proxy"


def test_server_mjs_catchall_proxy_has_auth():
    """The catch-all proxy must have requireAuth middleware.

    The catch-all is registered as:
      app.use('/api/aria', requireAuth, async (req, res, next) => { ... });
    The requireAuth is the second argument.
    """
    text = _read_server()
    # Find the catch-all proxy registration — look for app.use('/api/aria', requireAuth, ...
    # There are TWO app.use('/api/aria' calls: one is a comment about the multipart
    # pass-through, the other is the actual catch-all with requireAuth.
    idx = text.find("app.use('/api/aria', requireAuth")
    assert idx >= 0, (
        "Could not find app.use('/api/aria', requireAuth in server.mjs. "
        "The catch-all proxy must have requireAuth middleware."
    )
    # Verify it's the actual catch-all (not a comment)
    snippet = text[idx:idx+200]
    assert "requireAuth" in snippet, (
        f"Catch-all proxy missing requireAuth middleware. Snippet: {snippet[:200]}"
    )


def test_server_mjs_all_dd_routes_have_auth():
    """Every explicit /api/aria/dd/ route in server.mjs must have requireAuth."""
    text = _read_server()
    for m in re.finditer(
        r"""app\.(?:get|post|put|delete)\(['"]/api/aria/dd[^'"]*['"]""",
        text,
    ):
        route = m.group()
        assert "requireAuth" in text[m.start():m.start()+500], (
            f"DD route missing requireAuth: {route[:100]}"
        )


# ── 5. Critical endpoint smoke tests ────────────────────────────────────


@pytest.fixture()
def app():
    """Build a minimal FastAPI app with the DD router, no auth."""
    from fastapi import FastAPI
    from aria_service.routes import aria as aria_routes
    from types import SimpleNamespace

    app = FastAPI()
    app.dependency_overrides[aria_routes._router_auth_dep] = lambda: None
    app.include_router(aria_routes.router)
    app.state.llm_provider = SimpleNamespace(is_configured=True, name="fake")
    app.state.current_data = None
    return app


def _patch_dd_deps(monkeypatch):
    """Monkeypatch DD dependencies so tests are fast and deterministic."""
    from aria_service.intel import dd_orchestrator
    from aria_service.intel import dd_vault

    async def _fake_list_reports(limit=50, **kw):
        return [
            {
                "canonical_entity_id": "company_GB_TEST",
                "entity_name": "Test Co",
                "jurisdiction": "GB",
                "run_id": "test-run-1",
                "generated_at": "2026-07-01T10:00:00+00:00",
                "user_id": "test-user",
                "status": "completed",
                "mode": "standard",
            }
        ]

    async def _fake_get_case_file(cid, **kw):
        return {
            "canonical_entity_id": cid,
            "total_versions": 1,
            "versions": [{"run_id": "test-run-1", "generated_at": "2026-07-01T10:00:00+00:00"}],
        }

    class _FakeVault:
        def search(self, q, limit=50):
            return [{"canonical_entity_id": "company_GB_TEST", "entity_name": "Test Co"}]
        def list_all(self, limit=100):
            return self.search("", limit)
        def get_case(self, cid):
            return {"canonical_entity_id": cid, "entity_name": "Test Co"}
        def get_cross_references(self, cid, **_kw):   # R-F2697 ACL kwargs
            return []
        def get_related_cases(self, cid, **_kw):      # R-F2697 ACL kwargs
            return []
        def delete_case(self, cid):
            return True
        def stats(self):
            return {"total_cases": 1, "total_versions": 2}

    monkeypatch.setattr(dd_orchestrator, "list_reports", _fake_list_reports)
    monkeypatch.setattr(dd_orchestrator, "get_case_file", _fake_get_case_file)
    monkeypatch.setattr(dd_vault, "get_vault", lambda: _FakeVault())


def test_dd_reports_endpoint_returns_valid_shape(app, monkeypatch):
    """GET /api/aria/dd/reports must return a dict with 'reports' list (not 500)."""
    _patch_dd_deps(monkeypatch)
    from fastapi.testclient import TestClient

    with TestClient(app) as c:
        resp = c.get("/api/aria/dd/reports?limit=10")
        assert resp.status_code == 200, f"dd/reports returned {resp.status_code}: {resp.text[:200]}"
        data = resp.json()
        assert isinstance(data, dict), f"Expected dict, got {type(data)}"
        assert "reports" in data, f"Missing 'reports' key: {data.keys()}"
        if data["reports"]:
            assert "entity_name" in data["reports"][0], (
                f"Report missing entity_name: {data['reports'][0].keys()}"
            )


def test_dd_case_endpoint_returns_valid_shape(app, monkeypatch):
    """GET /api/aria/dd/case/:cid must return a case (not 500)."""
    _patch_dd_deps(monkeypatch)
    from fastapi.testclient import TestClient

    with TestClient(app) as c:
        resp = c.get("/api/aria/dd/case/company_GB_TEST")
        assert resp.status_code == 200, f"dd/case returned {resp.status_code}: {resp.text[:200]}"
        data = resp.json()
        assert isinstance(data, dict), f"Expected dict, got {type(data)}"
        assert "canonical_entity_id" in data


def test_dd_vault_search_endpoint_returns_valid_shape(app, monkeypatch):
    """GET /api/aria/dd/vault/search must return entries (not 500)."""
    _patch_dd_deps(monkeypatch)
    from fastapi.testclient import TestClient

    with TestClient(app) as c:
        resp = c.get("/api/aria/dd/vault/search?q=test")
        assert resp.status_code == 200, f"dd/vault/search returned {resp.status_code}: {resp.text[:200]}"
        data = resp.json()
        assert "entries" in data, f"Missing 'entries' key: {data.keys()}"


def test_dd_vault_stats_endpoint_returns_valid_shape(app, monkeypatch):
    """GET /api/aria/dd/vault/stats must return stats (not 500)."""
    _patch_dd_deps(monkeypatch)
    from fastapi.testclient import TestClient

    with TestClient(app) as c:
        resp = c.get("/api/aria/dd/vault/stats")
        assert resp.status_code == 200, f"dd/vault/stats returned {resp.status_code}: {resp.text[:200]}"
        data = resp.json()
        assert isinstance(data, dict), f"Expected dict, got {type(data)}"


def test_dd_vault_case_endpoint_returns_valid_shape(app, monkeypatch):
    """GET /api/aria/dd/vault/case/:cid must return a case (not 500)."""
    _patch_dd_deps(monkeypatch)
    from fastapi.testclient import TestClient

    with TestClient(app) as c:
        resp = c.get("/api/aria/dd/vault/case/company_GB_TEST")
        assert resp.status_code == 200, f"dd/vault/case returned {resp.status_code}: {resp.text[:200]}"
        data = resp.json()
        assert isinstance(data, dict), f"Expected dict, got {type(data)}"


def test_dd_watchlist_endpoint_returns_valid_shape(app, monkeypatch):
    """GET /api/aria/dd/watchlist must return watchlist entries (not 500)."""
    _patch_dd_deps(monkeypatch)
    from fastapi.testclient import TestClient

    with TestClient(app) as c:
        resp = c.get("/api/aria/dd/watchlist")
        assert resp.status_code == 200, f"dd/watchlist returned {resp.status_code}: {resp.text[:200]}"
        data = resp.json()
        assert isinstance(data, dict), f"Expected dict, got {type(data)}"


def test_dd_watchlist_alerts_endpoint_returns_valid_shape(app, monkeypatch):
    """GET /api/aria/dd/watchlist/alerts must return alerts (not 500)."""
    _patch_dd_deps(monkeypatch)
    from fastapi.testclient import TestClient

    with TestClient(app) as c:
        resp = c.get("/api/aria/dd/watchlist/alerts?since_hours=168")
        assert resp.status_code == 200, f"dd/watchlist/alerts returned {resp.status_code}: {resp.text[:200]}"
        data = resp.json()
        assert isinstance(data, dict), f"Expected dict, got {type(data)}"


def test_dd_health_endpoint_returns_valid_shape(app, monkeypatch):
    """GET /api/aria/dd/health must return health status (not 500)."""
    _patch_dd_deps(monkeypatch)
    from fastapi.testclient import TestClient

    with TestClient(app) as c:
        resp = c.get("/api/aria/dd/health")
        assert resp.status_code == 200, f"dd/health returned {resp.status_code}: {resp.text[:200]}"
        data = resp.json()
        assert isinstance(data, dict), f"Expected dict, got {type(data)}"


def test_dd_layer_5c_stats_endpoint_returns_valid_shape(app, monkeypatch):
    """GET /api/aria/dd/layer-5c/stats must return stats (not 500)."""
    _patch_dd_deps(monkeypatch)
    from fastapi.testclient import TestClient

    with TestClient(app) as c:
        resp = c.get("/api/aria/dd/layer-5c/stats")
        assert resp.status_code == 200, f"dd/layer-5c/stats returned {resp.status_code}: {resp.text[:200]}"
        data = resp.json()
        assert isinstance(data, dict), f"Expected dict, got {type(data)}"


def test_dd_case_archive_stats_endpoint_returns_valid_shape(app, monkeypatch):
    """GET /api/aria/dd/case-archive/stats must return stats (not 500)."""
    _patch_dd_deps(monkeypatch)
    from fastapi.testclient import TestClient

    with TestClient(app) as c:
        resp = c.get("/api/aria/dd/case-archive/stats")
        assert resp.status_code == 200, f"dd/case-archive/stats returned {resp.status_code}: {resp.text[:200]}"
        data = resp.json()
        assert isinstance(data, dict), f"Expected dict, got {type(data)}"


def test_dd_sources_endpoint_returns_valid_shape(app, monkeypatch):
    """GET /api/aria/dd/sources must return sources (not 500)."""
    _patch_dd_deps(monkeypatch)
    from fastapi.testclient import TestClient

    with TestClient(app) as c:
        resp = c.get("/api/aria/dd/sources")
        assert resp.status_code == 200, f"dd/sources returned {resp.status_code}: {resp.text[:200]}"
        data = resp.json()
        assert isinstance(data, dict), f"Expected dict, got {type(data)}"


# ── 6. Cross-page consistency ───────────────────────────────────────────


def test_dd_reports_and_watchlist_share_api_patterns():
    """The DD reports page and watchlist page must use consistent API patterns."""
    dd_html = _read("dd-reports.html")
    wl_html = _read("watchlist.html")

    dd_calls = _extract_api_calls(dd_html)
    wl_calls = _extract_api_calls(wl_html)

    # Both pages should call /api/aria/dd/watchlist
    assert "/api/aria/dd/watchlist" in dd_calls or "/api/aria/dd/watchlist" in wl_calls, (
        "Neither page calls /api/aria/dd/watchlist"
    )

    # Both pages should call /api/aria/dd/orchestrate
    assert "/api/aria/dd/orchestrate" in dd_calls or "/api/aria/dd/orchestrate" in wl_calls, (
        "Neither page calls /api/aria/dd/orchestrate"
    )


def test_all_dd_pages_have_sidebar_and_header():
    """Every DD-related page must include the sidebar and header."""
    for page in ["dd-reports.html", "watchlist.html", "vls-chain.html"]:
        html = _read(page)
        assert "sidebar-placeholder" in html, f"{page} is missing sidebar-placeholder"
        assert "header-placeholder" in html, f"{page} is missing header-placeholder"


def test_all_dd_pages_have_auth_require():
    """Every DD-related page must call Auth.requireAuth()."""
    for page in ["dd-reports.html", "watchlist.html", "vls-chain.html"]:
        html = _read(page)
        assert "Auth.requireAuth" in html, f"{page} is missing Auth.requireAuth()"


# ── 7. Report detail view buttons ────────────────────────────────────────


def test_dd_reports_detail_view_has_all_action_buttons():
    """The report detail view must have all expected action buttons."""
    html = _read("dd-reports.html")

    # Check for the detail view action buttons
    expected_actions = ["rerun", "copy", "delete", "vls-verify", "vls-proof", "case-file"]
    actions = _find_data_actions(html)

    for action in expected_actions:
        assert action in actions, (
            f"Report detail view is missing data-action='{action}' button"
        )


def test_dd_reports_detail_view_rerun_wired():
    """The rerun button must call /api/aria/dd/orchestrate."""
    html = _read("dd-reports.html")
    assert "/api/aria/dd/orchestrate" in html, (
        "dd-reports.html does not call /api/aria/dd/orchestrate (rerun needs it)"
    )


def test_dd_reports_detail_view_delete_wired():
    """The delete button must call the by-run DD report delete endpoint."""
    html = _read("dd-reports.html")
    assert "/api/aria/dd/report/" in html, (
        "dd-reports.html does not call /api/aria/dd/report/ (delete needs it)"
    )
    assert "{ method: 'DELETE' }" in html, "dd-reports.html delete path is missing DELETE method"


def test_dd_reports_delete_removes_row_without_manual_refresh():
    """R-F2387 — any verified backend delete layer must remove the row locally."""
    html = _read("dd-reports.html")
    assert "function deleteVerified(result)" in html
    assert "result.vault_deleted" in html, (
        "deleteVerified must accept persistent vault deletion, not only Redis/index deletion"
    )
    # R-F3532 — assert the PROPERTY (both delete call sites suppress the row
    # locally), not the exact argument list. These pinned `removeDeletedReport(runId)`
    # and went red when the receipt was threaded through so the whole deleted
    # VERSION CHAIN could be suppressed — a change that strengthens the very
    # behaviour this test protects.
    import re as _re
    assert len(_re.findall(r"removeDeletedReport\(runId\b", html)) >= 1
    assert len(_re.findall(r"removeDeletedReport\(rid\b", html)) >= 1
    assert "_locallyDeletedRunIds.add(runId)" in html
    assert "_locallyDeletedRunIds.has(r.run_id)" in html
    # R-F3532 — and the suppression must cover every run the cascade removed,
    # otherwise the previous version resurfaces as the row on the next poll.
    assert "result.deleted_run_ids" in html, (
        "only the clicked run is suppressed — an earlier version will come back as the row"
    )


def test_dd_reports_detail_view_vls_wired():
    """The VLS buttons must call /api/aria/dd/vls/ endpoints.

    The VLS chain page is a separate page (vls-chain.html), so dd-reports.html
    only calls proof, verify, and key endpoints directly. The chain endpoint
    is called from vls-chain.html.
    """
    html = _read("dd-reports.html")
    assert "/api/aria/dd/vls/proof/" in html, (
        "dd-reports.html does not call /api/aria/dd/vls/proof/"
    )
    assert "/api/aria/dd/vls/verify/" in html, (
        "dd-reports.html does not call /api/aria/dd/vls/verify/"
    )
    assert "/api/aria/dd/vls/key" in html, (
        "dd-reports.html does not call /api/aria/dd/vls/key"
    )

    # The chain endpoint is on the separate vls-chain.html page
    vls_html = _read("vls-chain.html")
    assert "/api/aria/dd/vls/chain/" in vls_html, (
        "vls-chain.html does not call /api/aria/dd/vls/chain/"
    )


# ── 8. Watchlist page action buttons ─────────────────────────────────────


def test_watchlist_has_add_entity_button():
    """The watchlist page must have an 'Add Entity' button wired to POST /api/aria/dd/watchlist."""
    html = _read("watchlist.html")
    assert "wl-add-btn" in html, "watchlist.html is missing wl-add-btn"
    assert "/api/aria/dd/watchlist" in html, (
        "watchlist.html does not call /api/aria/dd/watchlist (add needs it)"
    )


def test_watchlist_has_rescreen_button():
    """The watchlist page must have a 'Re-screen All' button wired to POST /api/aria/dd/watchlist/rescreen.

    R-F3271 — this guard was RIGHT and had been red for weeks. R-F3225 deleted the
    button and its whole handler under a commit message that said only "focused
    page copy cleanup", leaving the backend endpoint orphaned and users with no way
    to trigger a re-screen. Restored, and the R-number is named here so the R-F559
    verifier can find the test that covers it.
    """
    html = _read("watchlist.html")
    assert "wl-rescreen-btn" in html, "watchlist.html is missing wl-rescreen-btn"
    assert "/api/aria/dd/watchlist/rescreen" in html, (
        "watchlist.html does not call /api/aria/dd/watchlist/rescreen"
    )


def test_watchlist_has_search():
    """The watchlist page must have a search input."""
    html = _read("watchlist.html")
    assert "wl-search" in html, "watchlist.html is missing wl-search input"


def test_watchlist_has_dd_reports_link():
    """The watchlist page must have a link to the DD reports page."""
    html = _read("watchlist.html")
    assert "dd-reports.html" in html, (
        "watchlist.html is missing link to dd-reports.html"
    )


def test_watchlist_has_alerts_section():
    """The watchlist page must have an alerts section."""
    html = _read("watchlist.html")
    assert "wl-alerts-section" in html, "watchlist.html is missing wl-alerts-section"
    assert "wl-alerts" in html, "watchlist.html is missing wl-alerts div"


def test_watchlist_per_row_buttons_have_delegated_handler():
    """The per-row DD and Remove buttons must use event delegation (not inline onclick)."""
    html = _read("watchlist.html")
    # Check for the delegated click handler
    assert "content.addEventListener('click'" in html or 'content.addEventListener("click"' in html, (
        "watchlist.html is missing the delegated click handler"
    )
    # Check for the action button classes
    assert "wl-act-dd" in html, "watchlist.html is missing wl-act-dd class"
    assert "wl-act-remove" in html, "watchlist.html is missing wl-act-remove class"


# ── 9. VLS chain page buttons ────────────────────────────────────────────


def test_vls_chain_has_all_expected_buttons():
    """The VLS chain page must have all expected interactive elements."""
    html = _read("vls-chain.html")
    ids = _find_ids(html)
    expected_ids = [
        "vls-search",
        "vls-content",
        "vls-key-btn",
    ]
    for eid in expected_ids:
        assert eid in ids, f"vls-chain.html is missing id='{eid}'"


def test_vls_chain_api_calls_wired():
    """The VLS chain page must call the VLS chain API endpoint."""
    html = _read("vls-chain.html")
    assert "/api/aria/dd/vls/chain/" in html, (
        "vls-chain.html does not call /api/aria/dd/vls/chain/"
    )
