"""ARIA LLM Training Script — generated by ARIA LLM Pipeline."""
import json, torch
from datasets import Dataset
from transformers import (
    AutoModelForCausalLM, AutoTokenizer, TrainingArguments,
    BitsAndBytesConfig,
)
from peft import LoraConfig
from trl import SFTTrainer

# Load config
with open("training_config.json") as f:
    config = json.load(f)

# Load dataset
with open(config["dataset_file"]) as f:
    data = json.load(f)

dataset = Dataset.from_list([
    {"text": f"### Instruction:\n{d['instruction']}\n\n### Response:\n{d['response']}"}
    for d in data
])

# Quantization
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16,
)

# Load model
model = AutoModelForCausalLM.from_pretrained(
    config["model_name"],
    quantization_config=bnb_config,
    device_map="auto",
    trust_remote_code=True,
)
tokenizer = AutoTokenizer.from_pretrained(config["model_name"])
tokenizer.pad_token = tokenizer.eos_token

# LoRA
lora_config = LoraConfig(
    r=config["lora_r"],
    lora_alpha=config["lora_alpha"],
    lora_dropout=config["lora_dropout"],
    bias="none",
    task_type="CAUSAL_LM",
)

# Training
training_args = TrainingArguments(
    output_dir=config["output_dir"],
    per_device_train_batch_size=config["batch_size"],
    learning_rate=config["learning_rate"],
    num_train_epochs=config["num_epochs"],
    logging_steps=10,
    save_steps=100,
    fp16=True,
    report_to="none",
)

trainer = SFTTrainer(
    model=model,
    args=training_args,
    train_dataset=dataset,
    tokenizer=tokenizer,
    max_seq_length=config["max_seq_length"],
    peft_config=lora_config,
)

trainer.train()
model.save_pretrained(config["output_dir"] + "/final")
tokenizer.save_pretrained(config["output_dir"] + "/final")
print(f"Training complete. Model saved to {config['output_dir']}/final")
