import Link from 'next/link';
import { ChevronRight } from 'lucide-react';
import { Card, CardContent } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { DDRunForm } from '@/components/dd-run-form';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { PageHeader, EmptyState, UnavailableState } from '@/components/page-header';
import { tryApiServer } from '@/lib/api';
import { pickFirst, fmtDate, riskVariant } from '@/lib/format';

export const dynamic = 'force-dynamic';

interface Report {
  run_id?: string; entity_name?: string; jurisdiction?: string;
  severity?: string; worst_severity?: string; risk?: string; risk_classification?: string;
  version_number?: number; generated_at?: string; created_at?: string; timestamp?: string;
  status?: string; error?: string;
}

export default async function ReportsPage() {
  const { data, error } = await tryApiServer<{ reports?: Report[] }>('/api/aria/dd/reports?limit=100');
  const reports = Array.isArray(data) ? (data as Report[]) : data?.reports ?? [];

  return (
    <div data-aria-surface="next-customer-reports">
      <PageHeader title="DD Reports" description="Forensic due-diligence reports generated by ARIA." />

      <Card className="mb-6">
        <CardContent className="p-4">
          <DDRunForm />
        </CardContent>
      </Card>

      {error ? (
        <UnavailableState title="DD reports unavailable" />
      ) : reports.length === 0 ? (
        <EmptyState title="No reports yet" hint="Run a due-diligence check above to generate your first report." />
      ) : (
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Entity</TableHead>
              <TableHead>Jurisdiction</TableHead>
              <TableHead>Risk</TableHead>
              <TableHead>Version</TableHead>
              <TableHead>Generated</TableHead>
              <TableHead className="w-10" />
            </TableRow>
          </TableHeader>
          <TableBody>
            {reports.map((r, i) => {
              const status = String(r.status || '').toLowerCase();
              const risk = pickFirst(r.severity, r.worst_severity, r.risk, r.risk_classification);
              return (
                <TableRow key={r.run_id || i}>
                  <TableCell className="font-medium">{r.entity_name || 'Unnamed entity'}</TableCell>
                  <TableCell className="text-muted-foreground">{r.jurisdiction || '—'}</TableCell>
                  <TableCell>
                    {status === 'running' ? <Badge variant="secondary">Running</Badge>
                      : status === 'failed' ? <Badge variant="destructive">Failed</Badge>
                      : risk ? <Badge variant={riskVariant(risk)}>{String(risk)}</Badge> : '—'}
                  </TableCell>
                  <TableCell className="text-muted-foreground">{r.version_number ?? '—'}</TableCell>
                  <TableCell className="text-muted-foreground">{fmtDate(pickFirst(r.generated_at, r.created_at, r.timestamp))}</TableCell>
                  <TableCell>
                    {r.run_id && status !== 'running' && status !== 'failed' ? (
                      <Link href={`/reports/${encodeURIComponent(r.run_id)}`} className="flex items-center gap-1 text-sm text-primary hover:underline">
                        Open <ChevronRight className="h-4 w-4" />
                      </Link>
                    ) : null}
                  </TableCell>
                </TableRow>
              );
            })}
          </TableBody>
        </Table>
      )}
    </div>
  );
}
