import Link from 'next/link';
import { Play, ChevronRight } from 'lucide-react';
import { Card, CardContent } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { PageHeader, EmptyState, UnavailableState } from '@/components/page-header';
import { tryApiServer } from '@/lib/api';
import { pickFirst, fmtDate, riskVariant } from '@/lib/format';
import { runDD } from '@/lib/actions';

export const dynamic = 'force-dynamic';

interface Report {
  run_id?: string; entity_name?: string; jurisdiction?: string;
  severity?: string; worst_severity?: string; risk?: string; risk_classification?: string;
  version_number?: number; generated_at?: string; created_at?: string; timestamp?: string;
}

export default async function ReportsPage() {
  const { data, error } = await tryApiServer<{ reports?: Report[] }>('/api/aria/dd/reports?limit=100');
  const reports = Array.isArray(data) ? (data as Report[]) : data?.reports ?? [];

  return (
    <div>
      <PageHeader title="DD Reports" description="Forensic due-diligence reports generated by ARIA." />

      <Card className="mb-6">
        <CardContent className="p-4">
          <form action={runDD} className="flex flex-col gap-3 sm:flex-row sm:items-center">
            <Input name="name" placeholder="Entity or company name…" className="sm:max-w-xs" required />
            <Input name="jurisdiction" placeholder="Jurisdiction (optional)" className="sm:max-w-[12rem]" />
            <select name="mode" className="h-10 rounded-md border border-input bg-background px-3 text-sm">
              <option value="standard">Standard</option>
              <option value="deep">Deep</option>
            </select>
            <Button type="submit" className="gap-2">
              <Play className="h-4 w-4" /> Run due diligence
            </Button>
          </form>
        </CardContent>
      </Card>

      {error ? (
        <UnavailableState title="DD reports unavailable" />
      ) : reports.length === 0 ? (
        <EmptyState title="No reports yet" hint="Run a due-diligence check above to generate your first report." />
      ) : (
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Entity</TableHead>
              <TableHead>Jurisdiction</TableHead>
              <TableHead>Risk</TableHead>
              <TableHead>Version</TableHead>
              <TableHead>Generated</TableHead>
              <TableHead className="w-10" />
            </TableRow>
          </TableHeader>
          <TableBody>
            {reports.map((r, i) => {
              const risk = pickFirst(r.severity, r.worst_severity, r.risk, r.risk_classification);
              return (
                <TableRow key={r.run_id || i}>
                  <TableCell className="font-medium">{r.entity_name || 'Unnamed entity'}</TableCell>
                  <TableCell className="text-muted-foreground">{r.jurisdiction || '—'}</TableCell>
                  <TableCell>{risk ? <Badge variant={riskVariant(risk)}>{String(risk)}</Badge> : '—'}</TableCell>
                  <TableCell className="text-muted-foreground">{r.version_number ?? '—'}</TableCell>
                  <TableCell className="text-muted-foreground">{fmtDate(pickFirst(r.generated_at, r.created_at, r.timestamp))}</TableCell>
                  <TableCell>
                    {r.run_id ? (
                      <Link href={`/reports/${encodeURIComponent(r.run_id)}`} className="flex items-center gap-1 text-sm text-primary hover:underline">
                        Open <ChevronRight className="h-4 w-4" />
                      </Link>
                    ) : null}
                  </TableCell>
                </TableRow>
              );
            })}
          </TableBody>
        </Table>
      )}
    </div>
  );
}
