# =============================================================================
# ARIA v3.1 — Active Challenge Engine
# aria_service/intel/active_challenge_engine.py
#
# WHAT THIS SOLVES:
#   ARIA currently listens and logs. This module makes her interject.
#   When the team converges on a decision, ARIA surfaces counterarguments.
#   When a counterparty makes a claim, ARIA questions its consistency.
#   When an assumption goes unstated, ARIA names it.
#
# INTEGRATION POINTS:
#   → aria_zoom_service.py: feed live captions here
#   → email/WhatsApp ingest: feed inbound messages here
#   → deal pipeline: feed deal context here
#   → delivery: post challenges to Zoom chat / team DM / WhatsApp
#
# DESIGN PRINCIPLE:
#   The challenge must be specific to the conversation, not generic.
#   A generic "have you considered the risks?" is useless.
#   A specific "you haven't asked who the UBO of this entity is,
#   and the ORSR shows three directors who are all PEP-adjacent" is valuable.
#
# AUTONOMY TIER: Tier 1 — Auto-allowed (internal channels only, no external send)
# =============================================================================

import re
import json
import logging
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Optional
from enum import Enum

import os
import anthropic
from aria_service.config import Settings

_settings = Settings()


class _ConfigShim:
    """Matches the attribute access pattern config.X used below."""
    @property
    def anthropic_api_key(self) -> str:
        return _settings.anthropic_api_key or os.getenv("ANTHROPIC_API_KEY", "")

    @property
    def model_standard(self) -> str:
        return os.getenv("ARIA_CHALLENGE_MODEL", "claude-sonnet-4-5")


config = _ConfigShim()

logger = logging.getLogger("ARIA.ActiveChallenge")


# =============================================================================
# CHALLENGE TYPES
# =============================================================================

class ChallengeType(Enum):
    DEVIL_ADVOCATE    = "DEVIL_ADVOCATE"     # Counterargument to consensus
    DD_GAP            = "DD_GAP"             # Missing due diligence question
    ASSUMPTION        = "ASSUMPTION"          # Unstated assumption surfaced
    CONTRADICTION     = "CONTRADICTION"       # Inconsistency with prior statement
    RISK_BLIND_SPOT   = "RISK_BLIND_SPOT"    # Risk the team hasn't named
    COMPLIANCE_FLAG   = "COMPLIANCE_FLAG"    # Regulatory or legal gap


class ChallengeUrgency(Enum):
    IMMEDIATE = "IMMEDIATE"  # Post to channel now
    DEFERRED  = "DEFERRED"   # Add to end-of-meeting summary
    WEEKLY    = "WEEKLY"     # Surface in weekly assumption audit


# =============================================================================
# DEAL CONTEXT — what ARIA knows about the current deal
# =============================================================================

@dataclass
class DealContext:
    """
    Everything ARIA knows about the deal being discussed.
    Passed in from the deal pipeline before the meeting starts.
    """
    deal_name: str = ""
    deal_type: str = ""       # broker | oem | end_user | g2g | unknown
    stage: str = ""           # qualification | due_diligence | negotiation | closing
    counterparty_name: str = ""
    counterparty_country: str = ""
    programme_value_usd: float = 0.0
    prior_claims: list[dict] = field(default_factory=list)
    open_dd_items: list[str] = field(default_factory=list)
    known_risks: list[str] = field(default_factory=list)
    last_meeting_summary: str = ""


# =============================================================================
# CHALLENGE OUTPUT
# =============================================================================

@dataclass
class Challenge:
    """A single challenge generated by ARIA."""
    challenge_type: ChallengeType
    urgency: ChallengeUrgency
    text: str                          # The challenge text for posting
    relevance_score: float = 0.0       # 0-1 — only post if > threshold
    trigger_statement: str = ""        # The statement that triggered this
    evidence: list[str] = field(default_factory=list)
    recommended_action: str = ""
    generated_at: str = field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )

    def to_chat_message(self) -> str:
        """Format for Zoom chat or WhatsApp posting."""
        prefix = {
            ChallengeType.DEVIL_ADVOCATE: "[ARIA — DEVIL'S ADVOCATE]",
            ChallengeType.DD_GAP:         "[ARIA — DD GAP]",
            ChallengeType.ASSUMPTION:     "[ARIA — UNSTATED ASSUMPTION]",
            ChallengeType.CONTRADICTION:  "[ARIA — CONTRADICTION FLAGGED]",
            ChallengeType.RISK_BLIND_SPOT:"[ARIA — BLIND SPOT]",
            ChallengeType.COMPLIANCE_FLAG:"[ARIA — COMPLIANCE]",
        }.get(self.challenge_type, "[ARIA]")

        lines = [prefix, "", self.text]
        if self.recommended_action:
            lines += ["", f"→ {self.recommended_action}"]
        if self.evidence:
            lines += ["", "Evidence:"]
            for e in self.evidence[:2]:
                lines.append(f"  • {e}")
        return "\n".join(lines)


# =============================================================================
# DD CHECKLIST TAXONOMY
# What questions must be asked, by deal type
# =============================================================================

DD_CHECKLISTS = {
    "broker": [
        "Who is the ultimate beneficial owner (UBO) of this intermediary?",
        "Has this broker been screened on all six sanctions lists (OFAC, HMT, EU, UN, OpenSanctions, ICC)?",
        "What is the stated basis for the broker's mandate — is there a signed document?",
        "Has the commission structure been disclosed and agreed in writing?",
        "Are there any prior regulatory actions or adverse media against this entity?",
        "Is the broker registered under any brokering licence regime?",
        "What is the source of their claimed relationship with the end-user?",
        "Have all directors been individually screened and PEP-assessed?",
        "Has the entity's banking relationship been established (no cash payments)?",
        "Is the commission being paid to the same entity that signed the agreement?",
    ],
    "oem": [
        "Does this OEM hold an AQAP-2110 or equivalent quality certification?",
        "Is the equipment subject to ITAR, EAR, or equivalent export controls?",
        "Has an end-user certificate been received and verified?",
        "Does the OEM have a registered entity in the UK or EU for SITCL compliance?",
        "What is the OEM's track record of delivery on comparable contracts?",
        "Are there any past export licence violations or regulatory actions?",
        "Has technology transfer scope been defined and agreed?",
        "What is the through-life support and spare parts commitment?",
        "Has the equipment been tested to the relevant STANAG or AECTP standard?",
        "Is the OEM's insurance adequate for the transaction value?",
    ],
    "end_user": [
        "Is the end-user country subject to UN, EU, or UK arms embargo?",
        "Has the end-user signatory been verified as holding the stated position?",
        "Is the signatory authority to sign EUCs on behalf of the ministry confirmed?",
        "Has the end-user been screened on all sanctions lists?",
        "Is there a no-diversion clause in the end-user certificate?",
        "Has UK Criterion 2 been assessed for this end-user?",
        "Is the stated end-use consistent with the recipient country's legitimate defence needs?",
        "Has ECJU been consulted on any ATT Article 7 concerns?",
        "Is the end-user a PEP or associated with a PEP?",
        "What is the payment structure and does it avoid sanctioned financial channels?",
    ],
    "g2g": [
        "Has the G2G arrangement been reviewed by ECJU and agreed in writing?",
        "Is there a formal government-to-government agreement underpinning this?",
        "Has the receiving government's financial position been assessed?",
        "Is the receiving government subject to any bilateral or multilateral restrictions?",
        "Has the programme been officially notified through diplomatic channels?",
        "Are offset or industrial participation requirements defined?",
        "Is there a force majeure provision appropriate for government counterparty?",
        "Has the export licence pathway been agreed with ECJU pre-LOA?",
        "Is the payment mechanism government-guaranteed or escrow-backed?",
        "Has the programme been reported to the appropriate oversight body?",
    ],
}

# Assumptions that are frequently made without being stated, by deal stage
COMMON_UNSTATED_ASSUMPTIONS = {
    "qualification": [
        "The counterparty has the financial capacity to complete this transaction",
        "The stated timeline is operationally realistic",
        "The end-user actually wants what the broker claims they want",
        "The counterparty's mandate is current and not expired",
        "No competitor has already established preferred supplier status",
    ],
    "due_diligence": [
        "The documents provided are genuine and not falsified",
        "The officials named in the EUC are still in post",
        "The stated budget has been formally allocated, not merely discussed",
        "The UBO disclosed is the actual controlling interest",
        "The country's political situation is stable enough to complete the transaction",
    ],
    "negotiation": [
        "The counterparty's decision-maker is the person in the room",
        "The agreed terms will survive a change of government or minister",
        "The payment mechanism the counterparty proposed is compliant",
        "The timeline commitment is a firm commitment, not an aspiration",
        "The scope agreed today is the scope that will be delivered",
    ],
    "closing": [
        "The export licence will be granted within the required timeline",
        "The delivery schedule is achievable given current supply chain conditions",
        "The counterparty has not had any material change of circumstances since qualification",
        "The commission arrangement survives if the deal structure changes",
        "Post-delivery support is covered by the agreement as written",
    ],
}


# =============================================================================
# ACTIVE CHALLENGE ENGINE
# =============================================================================

class ARIAActiveChallengeEngine:
    """
    ARIA's active challenge capability.

    Transforms ARIA from a passive listener to an active analytical participant
    in meetings and deal conversations.

    Three modes:
    1. LIVE — processes meeting captions in real time, posts immediate challenges
    2. POST-MEETING — processes full transcript, surfaces deferred challenges
    3. WEEKLY — runs assumption audit across all active deals

    All challenges are internal-only (Tier 1 autonomy).
    No external sends. No client-facing outputs without human review.
    """

    RELEVANCE_THRESHOLD = 0.65   # Only post if relevance >= this
    MAX_CHALLENGES_PER_SEGMENT = 2  # Don't flood the channel

    # Patterns that indicate consensus forming — trigger devil's advocate
    CONSENSUS_PATTERNS = [
        r"\bwe(?:'re| are) (?:all )?(?:agreed|aligned|moving forward)\b",
        r"\blet'?s (?:proceed|go ahead|move forward|do this)\b",
        r"\beveryone(?:'s| is) (?:happy|comfortable|on board)\b",
        r"\bno (?:concerns|objections|issues)\b",
        r"\bwe(?:'ve| have) (?:decided|agreed|confirmed)\b",
        r"\bsounds? good\b.*\blet'?s\b",
        r"\bwe(?:'re| are) (?:good to go|ready to proceed)\b",
        r"\bi think we(?:'re| are) (?:done|there|sorted)\b",
    ]

    def __init__(self, deliver_fn=None):
        """
        Args:
            deliver_fn: Function that posts a challenge to the appropriate channel.
                        Signature: deliver_fn(challenge: Challenge, channel: str)
        """
        self.client = anthropic.Anthropic(api_key=config.anthropic_api_key)
        self.deliver = deliver_fn
        self._segment_buffer: list[str] = []
        self._challenges_this_meeting: list[Challenge] = []

    # ── LIVE MEETING MODE ─────────────────────────────────────────────────────

    def process_caption_segment(
        self,
        text: str,
        deal_context: DealContext,
        channel: str = "zoom_chat",
    ) -> list[Challenge]:
        """
        Process a segment of live meeting captions.
        Call this every 60-90 seconds with the latest caption text.

        Args:
            text:         New caption text since last call
            deal_context: Current deal context
            channel:      Where to post challenges

        Returns:
            List of challenges generated (may be empty)
        """
        if not text.strip():
            return []

        self._segment_buffer.append(text)
        # Analyse when buffer has accumulated ~300 words or consensus detected
        buffer_text = " ".join(self._segment_buffer)
        word_count = len(buffer_text.split())

        consensus_detected = any(
            re.search(pattern, buffer_text, re.IGNORECASE)
            for pattern in self.CONSENSUS_PATTERNS
        )

        if word_count < 150 and not consensus_detected:
            return []  # Not enough context yet

        # Generate challenges
        challenges = self._generate_challenges(buffer_text, deal_context)

        # Filter by relevance
        challenges = [c for c in challenges
                      if c.relevance_score >= self.RELEVANCE_THRESHOLD]

        # Limit volume
        immediate = [c for c in challenges
                     if c.urgency == ChallengeUrgency.IMMEDIATE]
        immediate = immediate[:self.MAX_CHALLENGES_PER_SEGMENT]

        # Deliver immediate challenges
        if self.deliver:
            for challenge in immediate:
                self.deliver(challenge, channel)

        self._challenges_this_meeting.extend(challenges)
        self._segment_buffer = []  # Reset buffer
        return challenges

    def end_of_meeting_summary(self, deal_context: DealContext) -> str:
        """
        Generate end-of-meeting challenge summary.
        Includes deferred challenges and unanswered DD gaps.
        """
        deferred = [c for c in self._challenges_this_meeting
                    if c.urgency == ChallengeUrgency.DEFERRED]
        dd_gaps = self._check_dd_gaps(
            asked_questions=[],  # Pass questions extracted from transcript
            deal_type=deal_context.deal_type,
        )

        lines = [
            "═" * 50,
            "ARIA — END OF MEETING CHALLENGE SUMMARY",
            f"Deal: {deal_context.deal_name}",
            f"Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}",
            "═" * 50,
        ]

        if deferred:
            lines += ["", f"DEFERRED CHALLENGES ({len(deferred)}):"]
            for i, c in enumerate(deferred, 1):
                lines.append(f"\n{i}. [{c.challenge_type.value}]")
                lines.append(f"   {c.text}")
                if c.recommended_action:
                    lines.append(f"   → {c.recommended_action}")

        if dd_gaps:
            lines += ["", f"DD GAPS — QUESTIONS NOT ASKED ({len(dd_gaps)}):"]
            for gap in dd_gaps[:5]:
                lines.append(f"  ⚠ {gap}")

        # Reset for next meeting
        self._challenges_this_meeting = []

        lines.append("\n" + "═" * 50)
        return "\n".join(lines)

    # ── DD GAP DETECTION ─────────────────────────────────────────────────────

    def check_dd_gaps(
        self,
        conversation_text: str,
        deal_type: str,
        deal_context: Optional[DealContext] = None,
    ) -> list[Challenge]:
        """
        Check which standard DD questions have not been asked.

        Args:
            conversation_text: Full conversation text to check against
            deal_type:        broker | oem | end_user | g2g
            deal_context:     Optional deal context for enhanced checking

        Returns:
            List of DD gap challenges
        """
        checklist = DD_CHECKLISTS.get(deal_type, DD_CHECKLISTS["broker"])
        text_lower = conversation_text.lower()
        gaps = []

        for question in checklist:
            # Check if the substance of this question has been addressed
            # Extract key terms from the question for keyword matching
            key_terms = self._extract_key_terms(question)
            addressed = sum(1 for term in key_terms if term in text_lower)

            if addressed < len(key_terms) * 0.5:  # Less than half the terms present
                gaps.append(question)

        if not gaps:
            return []

        challenges = []
        # Group gaps into a single challenge if there are many
        if len(gaps) >= 3:
            challenge = Challenge(
                challenge_type=ChallengeType.DD_GAP,
                urgency=ChallengeUrgency.IMMEDIATE,
                text=(
                    f"{len(gaps)} standard DD questions for a {deal_type} arrangement "
                    f"have not been addressed in this conversation:\n\n"
                    + "\n".join(f"  • {g}" for g in gaps[:5])
                    + (f"\n  ... and {len(gaps)-5} more." if len(gaps) > 5 else "")
                ),
                relevance_score=0.85,
                recommended_action=(
                    f"Address the critical items before proceeding. "
                    f"ARIA can draft the questions if needed."
                ),
                evidence=gaps[:3],
            )
            challenges.append(challenge)
        else:
            for gap in gaps:
                challenges.append(Challenge(
                    challenge_type=ChallengeType.DD_GAP,
                    urgency=ChallengeUrgency.DEFERRED,
                    text=f"This question was not asked: {gap}",
                    relevance_score=0.75,
                    recommended_action="Ask before next meeting or counterparty contact.",
                ))

        return challenges

    # ── ASSUMPTION AUDITOR ────────────────────────────────────────────────────

    def audit_assumptions(
        self,
        conversation_text: str,
        deal_context: DealContext,
    ) -> list[Challenge]:
        """
        Extract and surface unstated assumptions in the conversation.

        Uses both pattern matching (fast) and LLM analysis (thorough).
        """
        challenges = []
        text_lower = conversation_text.lower()
        stage = deal_context.stage or "qualification"

        # Check standard unstated assumptions for this deal stage
        stage_assumptions = COMMON_UNSTATED_ASSUMPTIONS.get(stage, [])
        for assumption in stage_assumptions:
            # Check if this assumption has been explicitly validated in the conversation
            key_terms = self._extract_key_terms(assumption)
            tested = any(term in text_lower for term in key_terms[:2])

            if not tested:
                challenges.append(Challenge(
                    challenge_type=ChallengeType.ASSUMPTION,
                    urgency=ChallengeUrgency.WEEKLY,
                    text=f"Unstated assumption detected: '{assumption}'",
                    relevance_score=0.70,
                    recommended_action=(
                        "Explicitly verify this assumption before the next deal stage decision."
                    ),
                ))

        # LLM-based assumption extraction for novel assumptions
        llm_assumptions = self._extract_assumptions_llm(
            conversation_text, deal_context
        )
        challenges.extend(llm_assumptions)

        return challenges

    # ── CORE CHALLENGE GENERATION (LLM) ──────────────────────────────────────

    def _generate_challenges(
        self,
        text: str,
        deal_context: DealContext,
    ) -> list[Challenge]:
        """
        Use Claude to generate specific, relevant challenges for the conversation.
        """
        system_prompt = f"""You are ARIA, an analytical AI team member at Arkmurus Group, 
a defence and security advisory firm. Your role in this meeting is to be the devil's advocate 
— to catch what the team might miss, challenge assumptions, and flag risks.

Current deal context:
  Deal: {deal_context.deal_name}
  Type: {deal_context.deal_type}
  Stage: {deal_context.stage}
  Counterparty: {deal_context.counterparty_name} ({deal_context.counterparty_country})
  Value: USD {deal_context.programme_value_usd:,.0f}
  Known risks: {', '.join(deal_context.known_risks[:3]) or 'none logged'}
  Prior claims by counterparty: {len(deal_context.prior_claims)} on record

RULES:
- Generate only challenges that are SPECIFIC to what was just said
- Do not generate generic risk warnings
- Each challenge must cite the specific statement that triggered it
- Score relevance 0.0-1.0 (only generate if you would score >= 0.65)
- Post type: internal team channel only — be direct, not diplomatic
- Maximum 3 challenges per response
- If nothing genuinely needs challenging, return empty array

Respond ONLY with JSON array. Example:
[
  {{
    "type": "DEVIL_ADVOCATE",
    "urgency": "IMMEDIATE",
    "text": "Specific challenge text here",
    "relevance_score": 0.85,
    "trigger_statement": "The exact statement that triggered this",
    "evidence": ["Supporting fact 1", "Supporting fact 2"],
    "recommended_action": "Specific action to take"
  }}
]"""

        try:
            response = self.client.messages.create(
                model=config.model_standard,
                max_tokens=1000,
                system=system_prompt,
                messages=[{
                    "role": "user",
                    "content": f"Meeting segment to analyse:\n\n{text[-2000:]}"
                }],
                timeout=30,
            )

            raw = response.content[0].text.strip()
            # Strip markdown fences if present
            raw = re.sub(r"```json\s*|\s*```", "", raw).strip()

            data = json.loads(raw)
            challenges = []
            for item in data:
                if not isinstance(item, dict):
                    continue
                c = Challenge(
                    challenge_type=ChallengeType[
                        item.get("type", "DEVIL_ADVOCATE")
                    ],
                    urgency=ChallengeUrgency[
                        item.get("urgency", "DEFERRED")
                    ],
                    text=item.get("text", ""),
                    relevance_score=float(item.get("relevance_score", 0.5)),
                    trigger_statement=item.get("trigger_statement", ""),
                    evidence=item.get("evidence", []),
                    recommended_action=item.get("recommended_action", ""),
                )
                if c.text:
                    challenges.append(c)
            return challenges

        except (json.JSONDecodeError, KeyError, ValueError) as e:
            logger.warning(f"Challenge generation parse error: {e}")
            return []
        except Exception as e:
            logger.error(f"Challenge generation failed: {e}")
            return []

    def _extract_assumptions_llm(
        self,
        text: str,
        deal_context: DealContext,
    ) -> list[Challenge]:
        """Extract novel unstated assumptions using LLM analysis."""
        try:
            prompt = f"""Analyse this business conversation and identify unstated assumptions 
the team is making. Focus on assumptions that:
1. Are not explicitly stated but are implied by the decisions being made
2. If false, would materially change the decision
3. Could be tested or verified

Deal context: {deal_context.deal_name}, {deal_context.deal_type} deal, 
{deal_context.stage} stage with {deal_context.counterparty_name}.

Conversation:
{text[-1500:]}

Return JSON array of assumptions only (max 3). Each:
{{"assumption": "...", "consequence_if_false": "...", "how_to_verify": "..."}}

Return [] if no material unstated assumptions found."""

            response = self.client.messages.create(
                model=config.model_standard,
                max_tokens=600,
                messages=[{"role": "user", "content": prompt}],
                timeout=20,
            )
            raw = re.sub(r"```json\s*|\s*```", "",
                         response.content[0].text.strip()).strip()
            items = json.loads(raw)
            challenges = []
            for item in items:
                if not isinstance(item, dict):
                    continue
                challenges.append(Challenge(
                    challenge_type=ChallengeType.ASSUMPTION,
                    urgency=ChallengeUrgency.DEFERRED,
                    text=f"Unstated assumption: {item.get('assumption', '')}",
                    relevance_score=0.72,
                    recommended_action=(
                        f"Verify: {item.get('how_to_verify', '')} | "
                        f"Risk if false: {item.get('consequence_if_false', '')}"
                    ),
                ))
            return challenges
        except Exception:
            return []

    def _check_dd_gaps(
        self, asked_questions: list[str], deal_type: str
    ) -> list[str]:
        """Return list of unanswered DD questions."""
        checklist = DD_CHECKLISTS.get(deal_type, [])
        asked_lower = " ".join(asked_questions).lower()
        return [
            q for q in checklist
            if not any(
                term in asked_lower
                for term in self._extract_key_terms(q)[:2]
            )
        ]

    def _extract_key_terms(self, text: str) -> list[str]:
        """Extract 2-4 key terms from a question or statement."""
        stop = {
            "the", "a", "an", "is", "are", "has", "have", "been", "this",
            "that", "what", "which", "where", "when", "who", "how", "been",
            "does", "do", "did", "will", "would", "could", "should", "any",
        }
        words = re.findall(r"\b[a-zA-Z]{4,}\b", text.lower())
        return [w for w in words if w not in stop][:4]
