// lib/auth/passwordRotation.mjs
//
// R-F3332 — a temporary password that was ISSUED to someone must be rotated
// before the account is usable.
//
// R-F3328 made design-partner approval mint a one-time password. That credential
// is generated by us, displayed on an admin's screen, and emailed in clear, so
// unlike a password the user chose at signup it is known to at least one other
// party by construction. The email and the admin panel both INSTRUCT the partner
// to change it — and instruction is not enforcement. Nothing stopped that
// credential living for the life of a full-platform account.
//
// WHERE THIS BINDS. The decision lives here, as one pure function, because the
// enforcement point is requireAuth in server.mjs — every authenticated API call
// — and a rule that important should not be a condition buried in a middleware
// that no test can reach. A front-end redirect would NOT be enforcement: that is
// exactly the R-F3311 shape (a page opting out of a client-side check while the
// server happily served it). The client redirect added alongside this is UX; the
// 403 below is the gate.
//
// The allowlist is the minimum a locked-out account needs to unlock itself, and
// nothing else:
//   * PUT  /api/auth/password  — the rotation itself
//   * GET  /api/auth/me        — so the client can discover why it is blocked
//   * POST /api/auth/logout    — never trap someone in a session they want out of
// Note the rotation route requires currentPassword, which the holder of a
// temporary credential has. No new endpoint, no second way in.

export const ROTATION_ALLOWED = Object.freeze([
  { method: 'PUT', path: '/api/auth/password' },
  { method: 'GET', path: '/api/auth/me' },
  { method: 'POST', path: '/api/auth/logout' },
]);

export const ROTATION_REQUIRED_CODE = 'password_change_required';

/**
 * Should this request be refused because the account still holds an issued
 * temporary credential?
 *
 * Method AND path are both checked. Allowing a path irrespective of method
 * would open every verb on it (a DELETE /api/auth/me is not the read the
 * allowlist is granting), and the whole point of this list is that it is the
 * smallest surface that still lets someone unlock their own account.
 *
 * @param {object|null} user  the LIVE user record, not the JWT payload — the
 *   token is minted at login and cannot know about a rotation that happened
 *   after it was issued
 * @param {string} method  HTTP method
 * @param {string} path    request path, without query string
 * @returns {boolean} true ⇒ refuse with 403 + ROTATION_REQUIRED_CODE
 */
export function rotationBlocked(user, method, path) {
  if (!user || !user.mustChangePassword) return false;
  const m = String(method || '').toUpperCase();
  // Compare the path only, never the raw URL: a query string must not be able
  // to change the decision, in either direction.
  const p = String(path || '').split('?')[0];
  const allowed = ROTATION_ALLOWED.some((a) => a.method === m && a.path === p);
  return !allowed;
}

/**
 * The fields to write when a password is successfully changed. Kept here next
 * to the gate so the set and the clear can never drift apart — a gate whose
 * clear path is somewhere else is how an account gets locked out permanently.
 */
export function rotationClearedFields(now = new Date()) {
  return { mustChangePassword: false, credentialRotatedAt: now.toISOString() };
}
